// Renders the COIL website from content.js (editable text) and data/data.js (generated by datos/construir_datos.py).
(function () {
  const C = window.COIL_CONTENT;
  const D = window.COIL_DATA;
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'}[c]));
  const COLOR = {ESP: 'var(--esp)', SVK: 'var(--svk)', MNE: 'var(--mne)', EUU: 'var(--ue)'};
  const NS = 'http://www.w3.org/2000/svg';

  // ---------- Home ----------
  $('titulo').textContent = C.title;
  $('subtitulo').textContent = C.subtitle;
  $('curso').textContent = C.course;
  $('periodo').textContent = C.period;
  $('provisional').hidden = !C.provisional;
  $('universidades').innerHTML = C.universities.map((u) =>
    `<a class="uni" href="${esc(u.url)}" target="_blank" rel="noopener"><img src="${esc(u.logo)}" alt="${esc(u.name)}">`
    + `<strong>${esc(u.name)}</strong><span>${esc(u.country)}</span></a>`).join('');
  $('outcomes').innerHTML = C.outcomes.map((o) => `<li>${esc(o)}</li>`).join('');
  // Teaching team: photo if available (img/team/...), otherwise initials in the colour of the university
  const colorUni = {'University of Seville': 'var(--esp)', 'Technical University of Košice': 'var(--svk)', 'University of Montenegro': 'var(--mne)'};
  // first name + first surname (with two given names, the surname is the second-to-last word)
  const iniciales = (n) => { const w = n.trim().split(/\s+/); const s = w.length >= 4 ? w[w.length - 2] : (w[1] || ''); return (w[0][0] + (s[0] || '')).toUpperCase(); };
  $('teachers').innerHTML = C.teachers.map((t) => `<article class="docente" style="--color-uni:${colorUni[t.university] || 'var(--ulysseus)'}">
      ${t.photo ? `<img class="foto" src="${esc(t.photo)}" alt="${esc(t.name)}">`
        : `<div class="foto iniciales" style="background:${colorUni[t.university] || 'var(--ulysseus)'}" aria-hidden="true">${esc(iniciales(t.name))}</div>`}
      <h3>${esc(t.name)}</h3>
      <p class="uni-docente">${esc(t.university)}</p>
      ${t.bio ? `<p class="bio">${esc(t.bio)}</p>` : ''}
      ${t.email ? `<a href="mailto:${esc(t.email)}">${esc(t.email)}</a>` : ''}
    </article>`).join('');

  $('intro-equipo').textContent = C.teamIntro || '';
  $('como-trabajamos').innerHTML = (C.teamWork || []).map((t) => `<li>${esc(t)}</li>`).join('');
  $('contactos').innerHTML = C.universities.map((u) => {
    const ts = C.teachers.filter((t) => t.university === u.name);
    return `<div class="contacto"><img src="${esc(u.logo)}" alt=""><div><strong>${esc(u.name)}</strong>
      ${ts.map((t) => `<br>${esc(t.name)}${t.email ? ` · <a href="mailto:${esc(t.email)}">${esc(t.email)}</a>` : ''}`).join('')}</div></div>`;
  }).join('');

  // ---------- Schedule ----------
  // Month calendars (Monday first); each COIL week is coloured by phase and can be clicked to see its details.
  const hoy = new Date(); hoy.setHours(0, 0, 0, 0);
  const fmt = (d) => d.toLocaleDateString('en-GB', {day: 'numeric', month: 'short'});
  const clave = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const fases = [...new Set(C.schedule.map((s) => s.phase))];
  const colorFase = (f) => `fase-${fases.indexOf(f) % 6}`;
  const semanaDe = new Map();  // 'yyyy-mm-dd' -> schedule entry
  for (const s of C.schedule) {
    const ini = new Date(s.start + 'T00:00:00');
    for (let i = 0; i < 7; i++) { const d = new Date(ini); d.setDate(ini.getDate() + i); semanaDe.set(clave(d), s); }
  }
  const primero = new Date(C.schedule[0].start + 'T00:00:00');
  const ultimo = new Date(C.schedule[C.schedule.length - 1].start + 'T00:00:00'); ultimo.setDate(ultimo.getDate() + 6);
  $('leyenda-fases').innerHTML = fases.map((f) => `<span><i class="${colorFase(f)}"></i>${esc(f)}</span>`).join('');
  let html = '';
  for (let m = new Date(primero.getFullYear(), primero.getMonth(), 1); m <= ultimo; m = new Date(m.getFullYear(), m.getMonth() + 1, 1)) {
    html += `<div class="mes"><h3>${m.toLocaleDateString('en-GB', {month: 'long', year: 'numeric'})}</h3><table><thead><tr>`
      + ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d) => `<th>${d}</th>`).join('') + '</tr></thead><tbody><tr>';
    const desfase = (m.getDay() + 6) % 7;  // Monday = 0
    html += '<td class="fuera"></td>'.repeat(desfase);
    const dias = new Date(m.getFullYear(), m.getMonth() + 1, 0).getDate();
    for (let d = 1; d <= dias; d++) {
      const f = new Date(m.getFullYear(), m.getMonth(), d);
      const s = semanaDe.get(clave(f));
      const col = (desfase + d - 1) % 7;
      if (col === 0 && d > 1) html += '</tr><tr>';
      const clases = [s ? `coil ${colorFase(s.phase)}` : '', col >= 5 ? 'finde' : '', +f === +hoy ? 'hoy' : ''].join(' ').trim();
      html += `<td class="${clases}"${s ? ` data-week="${s.week}" title="Week ${s.week}: ${esc(s.title)}"` : ''}>`
        + `<span class="num">${d}</span>${s && col === 0 ? `<span class="etq">W${s.week}${(C.sessions || []).some((x) => x.week === s.week) ? ' ●' : ''}</span>` : ''}</td>`;
    }
    html += '<td class="fuera"></td>'.repeat((7 - (desfase + dias) % 7) % 7) + '</tr></tbody></table></div>';
  }
  $('calendario').innerHTML = html;

  // Deliverable due date: the Sunday of the same week
  const vence = (s) => { const d = new Date(s.start + 'T00:00:00'); d.setDate(d.getDate() + 6);
    return d.toLocaleDateString('en-GB', {weekday: 'long', day: 'numeric', month: 'long'}) + ', 23:59 CET'; };
  // Session and submission links: a button when published, a note when not yet.
  // Every session has two slots (different days and times), each with its own Teams link.
  const franjas = (x) => {
    const ss = x.slots || [];
    const alguno = ss.some((h) => h.link);
    const filas = ss.map((h) => `<li><b>${esc(h.label)}</b> · ${esc(h.when)} ${h.link
      ? `<a class="boton-pdf boton-enlace" href="${esc(h.link)}" target="_blank" rel="noopener">Join ${esc(h.label)}</a>`
      : alguno ? '<span class="pendiente">Link coming soon</span>' : ''}</li>`).join('');
    const aviso = alguno ? ''
      : x.poll ? `<a class="boton-sec boton-enlace" href="${esc(x.poll)}" target="_blank" rel="noopener">Vote for the dates and times</a>`
      : '<span class="pendiente">The links will be published here before the session</span>';
    return `<ul class="franjas">${filas}</ul>${aviso}`;
  };
  const botonEnvio = (e) => e.submitLink
    ? `<a class="boton-pdf boton-enlace" href="${esc(e.submitLink)}" target="_blank" rel="noopener">Submit deliverable ${e.number}</a>`
    : '<span class="pendiente">The submission link will be published here</span>';
  // After the session: recording (when published) and slides
  const botonesDespues = (x) => `<p class="despues"><span class="despues-tit">Could not attend?</span> ${x.recording
    ? `<a class="boton-pdf boton-enlace" href="${esc(x.recording)}" target="_blank" rel="noopener">Watch the recording</a>`
    : '<span class="pendiente">The recording will be published here after the session</span>'}${x.slides ? ` <a class="boton-sec boton-enlace" href="${esc(x.slides)}" target="_blank" rel="noopener">Slides (PDF)</a>` : ''}</p>`;
  function fichaSesion(semana) {
    const x = (C.sessions || []).find((y) => y.week === semana);
    return x ? `<div class="sesion-aviso"><b>Joint session: ${esc(x.title)}</b> · ${esc(x.duration)}, on two different days <a href="#sessions">Details</a> ${franjas(x)}</div>` : '';
  }
  function fichaEntrega(s) {
    const e = s.deliverable;
    if (!e) {
      const sig = C.schedule.find((x) => x.deliverable && x.week > s.week);
      return `<div class="entrega sin"><p class="entrega-titulo">No deliverable this week</p>
        <p><b>By the end of the week:</b> ${esc(s.goal || '')}</p>
        ${sig ? `<p class="nota">Next deliverable: <strong>${esc(sig.deliverable.name)}</strong>, due ${esc(vence(sig))} (week ${sig.week}).</p>` : ''}</div>`;
    }
    return `<div class="entrega"><p class="entrega-titulo">Deliverable ${e.number}: ${esc(e.name)}</p>${e.note ? `<p class="nota">${esc(e.note)}</p>` : ''}
      <dl><dt>Due</dt><dd><strong>${esc(vence(s))}</strong></dd><dt>Who</dt><dd>${esc(e.who)}</dd>
      <dt>Format</dt><dd>${esc(e.format)}</dd><dt>Submit</dt><dd>${botonEnvio(e)}</dd></dl>
      <p class="entrega-sub">It must include:</p><ul>${e.include.map((i) => `<li>${esc(i)}</li>`).join('')}</ul></div>`;
  }

  function verSemana(n) {
    const s = C.schedule.find((x) => x.week === n);
    const ini = new Date(s.start + 'T00:00:00'); const fin = new Date(ini); fin.setDate(ini.getDate() + 6);
    document.querySelectorAll('#calendario td.coil').forEach((td) => td.classList.toggle('elegida', +td.dataset.week === n));
    $('detalle-semana').innerHTML = `<div class="cuando">Week ${s.week} · ${fmt(ini)} – ${fmt(fin)}</div>
      <span class="fase ${colorFase(s.phase)}">${esc(s.phase)}</span><h3>${esc(s.title)}</h3><p>${esc(s.activities)}</p>
      ${fichaSesion(s.week)}${fichaEntrega(s)}
      <div class="nav-semana">${n > 1 ? `<button data-ir="${n - 1}">← Week ${n - 1}</button>` : '<span></span>'}
      ${n < C.schedule.length ? `<button data-ir="${n + 1}">Week ${n + 1} →</button>` : ''}</div>`;
  }
  $('calendario').addEventListener('click', (e) => { const td = e.target.closest('td.coil'); if (td) verSemana(+td.dataset.week); });
  $('detalle-semana').addEventListener('click', (e) => { const b = e.target.closest('button[data-ir]'); if (b) verSemana(+b.dataset.ir); });
  const enCurso = semanaDe.get(clave(hoy));
  verSemana(enCurso ? enCurso.week : (hoy < primero ? 1 : C.schedule.length));

  // ---------- Student guide ----------
  $('guia').innerHTML = (C.guide || []).map((g, i) => `<details class="tema"${i === 0 ? ' open' : ''}>
      <summary>${esc(g.title)}</summary>
      ${(g.text || []).map((p) => `<p>${esc(p)}</p>`).join('')}
      ${g.items ? `<ul>${g.items.map((it) => `<li>${esc(it)}</li>`).join('')}</ul>` : ''}
    </details>`).join('');
  $('tabla-entregas').innerHTML = '<thead><tr><th>#</th><th>Week</th><th>Due</th><th>Deliverable</th><th>Who</th><th>Format</th><th>Submit</th></tr></thead><tbody>'
    + C.schedule.filter((s) => s.deliverable).map((s) => `<tr><td data-label="#">${s.deliverable.number}</td><td data-label="Week">${s.week}</td><td data-label="Due">${esc(vence(s).replace(', 23:59 CET', ''))}</td><td data-label="Deliverable"><strong>${esc(s.deliverable.name)}</strong></td>`
      + `<td data-label="Who">${esc(s.deliverable.who)}</td><td data-label="Format">${esc(s.deliverable.format)}</td><td data-label="Submit">${botonEnvio(s.deliverable)}</td></tr>`).join('') + '</tbody>';
  $('regla-entrega').innerHTML = `There are <strong>three deliverables</strong>. Each one is due on <strong>${esc(C.deadline)}</strong> of its week and is submitted on ${esc(C.submission)}. Click on a week in the schedule to see exactly what it must include. The other weeks are working weeks.`;
  const nombreInd = Object.fromEntries((window.COIL_DATA ? window.COIL_DATA.indicators : []).map((i) => [i.code, i.name]));
  const fichasEjemplos = C.examples.map((x, i) => `<article class="ejemplo">
      <figure class="ejemplo-foto">${x.image ? `<img src="${esc(x.image)}" alt="" loading="lazy">` : ''}
        <span class="ejemplo-num">${String(i + 1).padStart(2, '0')}</span><h3>${esc(x.title)}</h3></figure>
      <div class="ejemplo-cuerpo">
        <p class="pregunta">${esc(x.question)}</p>
        <p class="ejemplo-etq">Indicators</p>
        <ul class="chips">${x.indicators.map((k) => `<li title="${esc(k)}">${esc(nombreInd[k] || k)}</li>`).join('')}</ul>
        <p class="ejemplo-etq">Methods</p><p>${esc(x.methods)}</p>
        ${x.credit ? `<p class="credito">Photo: <a href="${esc(x.credit.url)}" target="_blank" rel="noopener">${esc(x.credit.author)}</a>, ${esc(x.credit.license)}, via Wikimedia Commons</p>` : ''}
      </div></article>`).join('');
  $('ejemplos-proyectos').innerHTML = fichasEjemplos;
  $('plantillas').innerHTML = C.templates.map((t) => `<details class="tema"><summary>${esc(t.title)}</summary>
      <ul>${t.items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul></details>`).join('');
  // simple line icons (24x24, stroke)
  const ICONOS = {
    certificate: '<circle cx="12" cy="9" r="5"/><path d="M9 13.5 7.5 21l4.5-2.5 4.5 2.5L15 13.5"/>',
    globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.8 3 2.8 15 0 18M12 3c-2.8 3-2.8 15 0 18"/>',
    portfolio: '<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M7 13l3-3 3 2 4-4M8 21h8M12 17v4"/>',
    skills: '<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',
    thesis: '<path d="M4 4h11l5 5v11H4z"/><path d="M15 4v5h5M8 13h8M8 17h6"/>',
    internship: '<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 13h18"/>',
    network: '<circle cx="12" cy="5" r="2.5"/><circle cx="5" cy="18" r="2.5"/><circle cx="19" cy="18" r="2.5"/><path d="M11 7.3 6.2 15.8M13 7.3l4.8 8.5M7.5 18h9"/>',
  };
  const icono = (k) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${ICONOS[k] || ''}</svg>`;
  const B = C.benefits;
  $('lead-beneficios').textContent = B.intro;
  $('cifras').innerHTML = B.points.map((p) => `<div class="cifra"><span class="valor">${esc(p.value)}</span><span class="escala">${esc(p.scale)}</span><span class="donde">${esc(p.where)}</span></div>`).join('');
  $('nota-puntos').textContent = B.pointsNote;
  $('texto-certificado').textContent = B.certificate;
  document.querySelector('.certificado .icono-grande').innerHTML = icono('certificate');
  $('beneficios').innerHTML = B.items.map((b) => `<article class="beneficio"><div class="icono">${icono(b.icon)}</div><div><h3>${esc(b.title)}</h3><p>${esc(b.text)}</p></div></article>`).join('');

  // ---------- Home: what is due this week ----------
  {
    const s = enCurso || C.schedule.find((x) => new Date(x.start + 'T00:00:00') > hoy) || C.schedule[C.schedule.length - 1];
    const empezado = !!enCurso;
    const fin = (x) => { const d = new Date(x.start + 'T00:00:00'); d.setDate(d.getDate() + 6); d.setHours(23, 59); return d; };
    const prox = C.schedule.find((x) => x.deliverable && fin(x) >= hoy);
    const proxSes = (C.sessions || []).find((x) => fin(C.schedule.find((y) => y.week === x.week)) >= hoy);
    $('esta-semana').innerHTML = `<p class="etiqueta">${empezado ? 'This week' : 'Coming up'} · Week ${s.week}: ${esc(s.title)}</p>
      ${prox ? `<p class="esta-entrega">Next deliverable: <strong>${esc(prox.deliverable.name)}</strong> · ${esc(prox.deliverable.who)} · due <strong>${esc(vence(prox))}</strong> ${botonEnvio(prox.deliverable)}</p>` : ''}
      ${proxSes ? `<p class="esta-entrega">Next joint session: <strong>${esc(proxSes.title)}</strong> (week ${proxSes.week}), on two different days: choose one with your team</p>${franjas(proxSes)}` : ''}
      <p class="accesos"><a class="boton-pdf" href="#schedule">See the schedule</a> <a class="boton-sec" href="#guide">Read the student guide</a>
      <a class="boton-sec" href="#benefits">Why join?</a> <a class="boton-sec" href="#faq">FAQ: do I need to code?</a></p>`;
  }

  // ---------- One section at a time ----------
  const vistas = new Set([...document.querySelectorAll('.vista')].map((s) => s.dataset.vista));
  function mostrarVista() {
    const v = vistas.has(location.hash.slice(1)) ? location.hash.slice(1) : 'home';
    document.querySelectorAll('.vista').forEach((s) => { s.hidden = s.dataset.vista !== v; });
    document.querySelectorAll('nav a').forEach((l) => l.classList.toggle('activo', l.getAttribute('href') === '#' + v));
    window.scrollTo(0, 0);
    abrirMenu(false);
  }
  // mobile menu (hamburger button, only visible on narrow screens)
  const botonMenu = $('boton-menu');
  function abrirMenu(si) {
    botonMenu.setAttribute('aria-expanded', si);
    document.querySelector('.cabecera').classList.toggle('menu-abierto', si);
  }
  botonMenu.addEventListener('click', () => abrirMenu(botonMenu.getAttribute('aria-expanded') !== 'true'));
  document.querySelectorAll('#menu a').forEach((l) => l.addEventListener('click', () => abrirMenu(false)));
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') abrirMenu(false); });
  window.addEventListener('hashchange', mostrarVista);
  mostrarVista();

  // ---------- Joint sessions ----------
  $('intro-sesiones').textContent = C.sessionsIntro || '';
  $('reglas-sesiones').innerHTML = (C.sessionRules || []).map((r) => `<li>${esc(r)}</li>`).join('');
  $('sesiones').innerHTML = (C.sessions || []).map((x) => {
    const sem = C.schedule.find((s) => s.week === x.week);
    const ini = new Date(sem.start + 'T00:00:00'); const fin = new Date(ini); fin.setDate(ini.getDate() + 6);
    return `<article class="sesion"><div class="sesion-cab"><span class="sesion-sem">Week ${x.week} · ${fmt(ini)} – ${fmt(fin)}</span>
      <h3>${esc(x.title)}</h3><p class="nota">${esc(x.duration)} · given twice, on two different days and times, same content</p>${franjas(x)}</div>
      <p><b>Goal:</b> ${esc(x.goal)}</p>
      <table class="agenda">${x.agenda.map((p) => `<tr><td>${p.min ? p.min + ' min' : ''}</td><td>${esc(p.item)}</td></tr>`).join('')}</table>
      <p class="entrega-sub">Before the session:</p><ul>${x.prepare.map((p) => `<li>${esc(p)}</li>`).join('')}</ul>${botonesDespues(x)}</article>`;
  }).join('');

  // ---------- Projects and resources ----------
  $('proyectos').innerHTML = C.projects.length
    ? C.projects.map((p) => `<article class="proyecto">${p.image ? `<img src="${esc(p.image)}" alt="">` : ''}
        <div><h3>${esc(p.team)}</h3><p class="nota">${esc((p.universities || []).join(' · '))}</p><p>${esc(p.topic)}</p>
        ${p.link ? `<a href="${esc(p.link)}" target="_blank" rel="noopener">Open dashboard</a>` : ''}</div></article>`).join('')
    : '<p class="vacio-proyectos">The final team projects will be published here after the joint online presentation (week 9).</p>';
  const idGrupo = (g) => 'faq-' + g.toLowerCase().replace(/[^a-z]+/g, '-');
  const ICONOS_FAQ = {
    start: '<path d="M5 12h14M13 6l6 6-6 6"/>',
    team: '<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c0-3.3 2.7-6 6-6s6 2.7 6 6M15 14.5c3 0 6 2 6 5"/>',
    video: '<rect x="3" y="6" width="13" height="12" rx="2"/><path d="M16 10l5-3v10l-5-3z"/>',
    check: '<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 12l3 3 5-6"/>',
    help: '<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.6V14M12 17h.01"/>',
  };
  const iconoFaq = (k) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONOS_FAQ[k] || ICONOS_FAQ.help}</svg>`;
  $('faq-indice').innerHTML = (C.faq || []).map((g) => `<a href="#${idGrupo(g.group)}"><span class="faq-ico">${iconoFaq(g.icon)}</span>${esc(g.group)}<span class="faq-n">${g.items.length}</span></a>`).join('');
  $('lista-faq').innerHTML = (C.faq || []).map((g, gi) => `<section class="faq-grupo" id="${idGrupo(g.group)}">
      <header class="faq-cab"><span class="faq-ico grande">${iconoFaq(g.icon)}</span><div><h3>${esc(g.group)}</h3>${g.intro ? `<p>${esc(g.intro)}</p>` : ''}</div></header>
      ${g.items.map((f, i) => `<details class="pregunta-faq"${gi === 0 && i === 0 ? ' open' : ''}><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</section>`).join('');
  // index links scroll inside the FAQ view instead of switching views; highlight the group in view
  const enlacesFaq = [...document.querySelectorAll('#faq-indice a')];
  enlacesFaq.forEach((l) => l.addEventListener('click', (e) => {
    e.preventDefault(); document.querySelector(l.getAttribute('href')).scrollIntoView({behavior: 'smooth', block: 'start'});
  }));
  if ('IntersectionObserver' in window) {
    const obs = new IntersectionObserver((ents) => ents.forEach((en) => {
      if (en.isIntersecting) enlacesFaq.forEach((l) => l.classList.toggle('activo', l.getAttribute('href') === '#' + en.target.id));
    }), {rootMargin: '-30% 0px -60% 0px'});
    document.querySelectorAll('.faq-grupo').forEach((s) => obs.observe(s));
  }
  $('materiales').innerHTML = (C.materials || []).map((g) => `<div class="material-grupo"><h3>${esc(g.group)}</h3>
    ${g.items.map((it) => `<div class="material"><p>${esc(it.title)}</p><p class="material-enlaces">${it.files.map(([l, f], i) =>
      `<a class="${i ? 'boton-sec' : 'boton-pdf'} boton-enlace" href="${esc(f)}" ${f.endsWith('.pdf') ? 'target="_blank" rel="noopener"' : 'download'}>${esc(l)}</a>`).join(' ')}</p></div>`).join('')}</div>`).join('');
  $('recursos').innerHTML = C.resources.map((r) => `<li><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></li>`).join('');

  // ---------- Data ----------
  if (!D) { $('data').insertAdjacentHTML('beforeend', '<p class="nota">Data file not found: run datos/construir_datos.py.</p>'); return; }
  const paises = Object.keys(D.countries).filter((p) => p !== 'EUU');
  $('n-paises').textContent = paises.length;
  $('rango-anios').textContent = `${D.from}–${D.to}`;
  document.querySelectorAll('.rango-anios').forEach((e) => { e.textContent = `${D.from} and ${D.to}`; });
  $('actualizado').textContent = D.updated;

  const temas = [...new Set(D.indicators.map((i) => i.theme))];
  $('indicador').innerHTML = temas.map((t) => `<optgroup label="${esc(t)}">`
    + D.indicators.filter((i) => i.theme === t).map((i) => `<option value="${esc(i.code)}">${esc(i.name)}</option>`).join('')
    + '</optgroup>').join('');

  const nodo = (tag, attrs, texto) => {
    const n = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, v);
    if (texto !== undefined) n.textContent = texto;
    return n;
  };
  const numero = (v) => (Math.abs(v) >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : Math.abs(v) >= 1000 ? Math.round(v).toLocaleString('en-GB') : (+v.toFixed(1)).toString());

  // charts are drawn at the real width of their box, so the labels keep their size on phones
  const ancho = (id) => Math.round(Math.min(520, Math.max(280, $(id).clientWidth || window.innerWidth - 90)));

  function lineas(codigo) {
    const W = ancho('grafico-lineas'), H = Math.round(W * 0.54), m = {l: 48, r: 12, t: 12, b: 28};
    const serie = D.series[codigo] || {};
    const claves = ['ESP', 'SVK', 'MNE', 'EUU'].filter((p) => serie[p]);
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Line chart'});
    const todos = claves.flatMap((p) => serie[p]);
    if (!todos.length) { $('grafico-lineas').innerHTML = '<p class="nota">No data for the three countries.</p>'; return; }
    const ys = todos.map((d) => d[1]);
    let y0 = Math.min(...ys), y1 = Math.max(...ys);
    if (y0 === y1) { y0 -= 1; y1 += 1; }
    const pad = (y1 - y0) * 0.08; y0 -= pad; y1 += pad;
    const x = (a) => m.l + (a - D.from) / (D.to - D.from) * (W - m.l - m.r);
    const y = (v) => H - m.b - (v - y0) / (y1 - y0) * (H - m.t - m.b);
    for (let k = 0; k <= 4; k++) {
      const v = y0 + (y1 - y0) * k / 4;
      svg.append(nodo('line', {x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), stroke: '#e3e1ea'}));
      svg.append(nodo('text', {x: m.l - 6, y: y(v) + 4, 'text-anchor': 'end'}, numero(v)));
    }
    for (let a = D.from; a <= D.to; a += 5) svg.append(nodo('text', {x: x(a), y: H - 8, 'text-anchor': 'middle'}, a));
    for (const p of claves) {
      const d = serie[p].map(([a, v], i) => `${i ? 'L' : 'M'}${x(a).toFixed(1)},${y(v).toFixed(1)}`).join('');
      svg.append(nodo('path', {d, fill: 'none', stroke: COLOR[p], 'stroke-width': p === 'EUU' ? 2 : 2.6,
        'stroke-dasharray': p === 'EUU' ? '5 4' : ''}));
      for (const [a, v] of serie[p]) {
        const c = nodo('circle', {cx: x(a), cy: y(v), r: 2.6, fill: COLOR[p]});
        c.append(nodo('title', {}, `${D.countries[p]}, ${a}: ${numero(v)}`));
        svg.append(c);
      }
    }
    const cont = $('grafico-lineas');
    cont.replaceChildren(svg);
    cont.insertAdjacentHTML('beforeend', '<div class="leyenda">' + ['ESP', 'SVK', 'MNE', 'EUU'].map((p) =>
      `<span><i style="background:${COLOR[p]}"></i>${esc(D.countries[p])}${serie[p] ? '' : ' (no data)'}</span>`).join('') + '</div>');
  }

  function ranking(codigo) {
    const serie = D.series[codigo] || {};
    // latest year with data for most countries
    const cuenta = {};
    for (const p of paises) for (const [a] of serie[p] || []) cuenta[a] = (cuenta[a] || 0) + 1;
    const anio = +Object.keys(cuenta).filter((a) => cuenta[a] >= paises.length * 0.6).sort().pop()
      || +Object.keys(cuenta).sort().pop();
    $('titulo-ranking').textContent = `All countries in ${anio || '—'}`;
    const filas = paises.map((p) => [p, (serie[p] || []).find((d) => d[0] === anio)]).filter((f) => f[1])
      .map(([p, d]) => [p, d[1]]).sort((a, b) => b[1] - a[1]);
    const W = ancho('grafico-ranking'), fila = 15, m = {l: W < 400 ? 132 : 150, r: W < 400 ? 34 : 48}, H = filas.length * fila + 8;
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Ranking bar chart'});
    const min = Math.min(0, ...filas.map((f) => f[1])), max = Math.max(0, ...filas.map((f) => f[1]));
    const x = (v) => m.l + (v - min) / ((max - min) || 1) * (W - m.l - m.r);
    filas.forEach(([p, v], i) => {
      const casa = D.home.includes(p);
      const yy = 4 + i * fila;
      svg.append(nodo('text', {x: m.l - 6, y: yy + 10, 'text-anchor': 'end', 'font-weight': casa ? 700 : 400,
        style: casa ? `fill:${COLOR[p]}` : ''}, D.countries[p]));
      svg.append(nodo('rect', {x: Math.min(x(0), x(v)), y: yy + 2, width: Math.max(1, Math.abs(x(v) - x(0))), height: fila - 4,
        fill: casa ? COLOR[p] : '#cfcbe0', rx: 2}));
      svg.append(nodo('text', {x: Math.max(x(0), x(v)) + 4, y: yy + 10}, numero(v)));
    });
    $('grafico-ranking').replaceChildren(svg);
    if (!filas.length) $('grafico-ranking').innerHTML = '<p class="nota">No data.</p>';
  }

  function mostrar() {
    const codigo = $('indicador').value;
    const ind = D.indicators.find((i) => i.code === codigo);
    $('ficha').textContent = `${ind.unit} · Source: ${ind.source} (code ${ind.code})`;
    lineas(codigo);
    ranking(codigo);
  }
  $('indicador').addEventListener('change', mostrar);
  mostrar();
  // redraw when the Data view is opened (it may have been hidden at load) or the screen is rotated
  window.addEventListener('hashchange', () => { if (location.hash === '#data') mostrar(); });
  let ultimoAncho = window.innerWidth, espera;
  window.addEventListener('resize', () => {
    if (window.innerWidth === ultimoAncho) return;
    ultimoAncho = window.innerWidth; clearTimeout(espera); espera = setTimeout(mostrar, 200);
  });

  // coverage table for the three COIL countries
  const cob = {};
  for (const c of D.coverage) cob[c.iso3 + '|' + c.indicator] = c;
  const total = D.to - D.from + 1;
  $('cobertura').innerHTML = '<thead><tr><th>Indicator</th>' + D.home.map((p) => `<th>${esc(D.countries[p])}</th>`).join('')
    + '</tr></thead><tbody>' + D.indicators.map((i) => '<tr><td>' + esc(i.name) + '</td>' + D.home.map((p) => {
      const c = cob[p + '|' + i.code];
      const n = c ? c.years : 0;
      const clase = n === 0 ? 'vacio' : n < total * 0.75 ? 'parcial' : '';
      return `<td class="n ${clase}">${n === 0 ? 'no data' : `${n} yrs <small>to ${c.last}</small>`}</td>`;
    }).join('') + '</tr>').join('') + '</tbody>';
})();
