// Renders the COIL website from content.js (editable text) and data/data.js (generated by datos/construir_datos.py).
(function () {
  const C = window.COIL_CONTENT;
  const D = window.COIL_DATA;
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'}[c]));
  const COLOR = {ESP: 'var(--esp)', SVK: 'var(--svk)', MNE: 'var(--mne)', EUU: 'var(--ue)'};
  const NS = 'http://www.w3.org/2000/svg';

  // ---------- Home ----------
  $('titulo').textContent = C.title;
  $('subtitulo').textContent = C.subtitle;
  $('curso').textContent = C.course;
  $('periodo').textContent = C.period;
  $('provisional').hidden = !C.provisional;
  $('universidades').innerHTML = C.universities.map((u) =>
    `<a class="uni" href="${esc(u.url)}" target="_blank" rel="noopener"><img src="${esc(u.logo)}" alt="${esc(u.name)}">`
    + `<strong>${esc(u.name)}</strong><span>${esc(u.country)}</span></a>`).join('');
  $('outcomes').innerHTML = C.outcomes.map((o) => `<li>${esc(o)}</li>`).join('');
  // Teaching team: photo if available (img/team/...), otherwise initials in the colour of the university
  const colorUni = {'Universidad de Sevilla': 'var(--esp)', 'Technical University of Košice': 'var(--svk)', 'University of Montenegro': 'var(--mne)'};
  // first name + first surname (with two given names, the surname is the second-to-last word)
  const iniciales = (n) => { const w = n.trim().split(/\s+/); const s = w.length >= 4 ? w[w.length - 2] : (w[1] || ''); return (w[0][0] + (s[0] || '')).toUpperCase(); };
  const logoUni = Object.fromEntries(C.universities.map((u) => [u.name, u.logo]));
  $('teachers').innerHTML = C.teachers.map((t) => `<article class="docente">
      ${t.photo ? `<img class="foto" src="${esc(t.photo)}" alt="${esc(t.name)}">`
        : `<div class="foto iniciales" style="background:${colorUni[t.university] || 'var(--ulysseus)'}" aria-hidden="true">${esc(iniciales(t.name))}</div>`}
      <h3>${esc(t.name)}</h3>
      <p class="uni-docente">${logoUni[t.university] ? `<img src="${esc(logoUni[t.university])}" alt="">` : ''}${esc(t.university)}</p>
      ${t.role ? `<p class="nota">${esc(t.role)}</p>` : ''}
      ${t.email ? `<a href="mailto:${esc(t.email)}">${esc(t.email)}</a>` : ''}
    </article>`).join('');

  // ---------- Schedule ----------
  const hoy = new Date();
  const fmt = (d) => d.toLocaleDateString('en-GB', {day: 'numeric', month: 'short'});
  $('semanas').innerHTML = C.schedule.map((s) => {
    const ini = new Date(s.start + 'T00:00:00');
    const fin = new Date(ini); fin.setDate(ini.getDate() + 6);
    const actual = hoy >= ini && hoy <= new Date(fin.getTime() + 864e5 - 1);
    return `<li class="semana${actual ? ' actual' : ''}">
      <div class="cuando">Week ${s.week}<small>${fmt(ini)} – ${fmt(fin)}</small></div>
      <div><span class="fase">${esc(s.phase)}</span><h3>${esc(s.title)}</h3><p>${esc(s.activities)}</p>
      <p class="entregable"><b>Deliverable:</b> ${esc(s.deliverable)}</p></div></li>`;
  }).join('');

  // ---------- Projects and resources ----------
  $('proyectos').innerHTML = C.projects.length
    ? C.projects.map((p) => `<article class="proyecto">${p.image ? `<img src="${esc(p.image)}" alt="">` : ''}
        <div><h3>${esc(p.team)}</h3><p class="nota">${esc((p.universities || []).join(' · '))}</p><p>${esc(p.topic)}</p>
        ${p.link ? `<a href="${esc(p.link)}" target="_blank" rel="noopener">Open dashboard</a>` : ''}</div></article>`).join('')
    : '<p class="vacio-proyectos">Team projects will be published here after the joint online presentation.</p>';
  $('recursos').innerHTML = C.resources.map((r) => `<li><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></li>`).join('');

  // ---------- Data ----------
  if (!D) { $('data').insertAdjacentHTML('beforeend', '<p class="nota">Data file not found: run datos/construir_datos.py.</p>'); return; }
  const paises = Object.keys(D.countries).filter((p) => p !== 'EUU');
  $('n-paises').textContent = paises.length;
  $('rango-anios').textContent = `${D.from}–${D.to}`;
  document.querySelectorAll('.rango-anios').forEach((e) => { e.textContent = `${D.from} and ${D.to}`; });
  $('actualizado').textContent = D.updated;

  const temas = [...new Set(D.indicators.map((i) => i.theme))];
  $('indicador').innerHTML = temas.map((t) => `<optgroup label="${esc(t)}">`
    + D.indicators.filter((i) => i.theme === t).map((i) => `<option value="${esc(i.code)}">${esc(i.name)}</option>`).join('')
    + '</optgroup>').join('');

  const nodo = (tag, attrs, texto) => {
    const n = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, v);
    if (texto !== undefined) n.textContent = texto;
    return n;
  };
  const numero = (v) => (Math.abs(v) >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : Math.abs(v) >= 1000 ? Math.round(v).toLocaleString('en-GB') : (+v.toFixed(1)).toString());

  function lineas(codigo) {
    const W = 520, H = 280, m = {l: 48, r: 12, t: 12, b: 28};
    const serie = D.series[codigo] || {};
    const claves = ['ESP', 'SVK', 'MNE', 'EUU'].filter((p) => serie[p]);
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Line chart'});
    const todos = claves.flatMap((p) => serie[p]);
    if (!todos.length) { $('grafico-lineas').innerHTML = '<p class="nota">No data for the three countries.</p>'; return; }
    const ys = todos.map((d) => d[1]);
    let y0 = Math.min(...ys), y1 = Math.max(...ys);
    if (y0 === y1) { y0 -= 1; y1 += 1; }
    const pad = (y1 - y0) * 0.08; y0 -= pad; y1 += pad;
    const x = (a) => m.l + (a - D.from) / (D.to - D.from) * (W - m.l - m.r);
    const y = (v) => H - m.b - (v - y0) / (y1 - y0) * (H - m.t - m.b);
    for (let k = 0; k <= 4; k++) {
      const v = y0 + (y1 - y0) * k / 4;
      svg.append(nodo('line', {x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), stroke: '#e3e1ea'}));
      svg.append(nodo('text', {x: m.l - 6, y: y(v) + 4, 'text-anchor': 'end'}, numero(v)));
    }
    for (let a = D.from; a <= D.to; a += 5) svg.append(nodo('text', {x: x(a), y: H - 8, 'text-anchor': 'middle'}, a));
    for (const p of claves) {
      const d = serie[p].map(([a, v], i) => `${i ? 'L' : 'M'}${x(a).toFixed(1)},${y(v).toFixed(1)}`).join('');
      svg.append(nodo('path', {d, fill: 'none', stroke: COLOR[p], 'stroke-width': p === 'EUU' ? 2 : 2.6,
        'stroke-dasharray': p === 'EUU' ? '5 4' : ''}));
      for (const [a, v] of serie[p]) {
        const c = nodo('circle', {cx: x(a), cy: y(v), r: 2.6, fill: COLOR[p]});
        c.append(nodo('title', {}, `${D.countries[p]}, ${a}: ${numero(v)}`));
        svg.append(c);
      }
    }
    const cont = $('grafico-lineas');
    cont.replaceChildren(svg);
    cont.insertAdjacentHTML('beforeend', '<div class="leyenda">' + ['ESP', 'SVK', 'MNE', 'EUU'].map((p) =>
      `<span><i style="background:${COLOR[p]}"></i>${esc(D.countries[p])}${serie[p] ? '' : ' (no data)'}</span>`).join('') + '</div>');
  }

  function ranking(codigo) {
    const serie = D.series[codigo] || {};
    // latest year with data for most countries
    const cuenta = {};
    for (const p of paises) for (const [a] of serie[p] || []) cuenta[a] = (cuenta[a] || 0) + 1;
    const anio = +Object.keys(cuenta).filter((a) => cuenta[a] >= paises.length * 0.6).sort().pop()
      || +Object.keys(cuenta).sort().pop();
    $('titulo-ranking').textContent = `All countries in ${anio || '—'}`;
    const filas = paises.map((p) => [p, (serie[p] || []).find((d) => d[0] === anio)]).filter((f) => f[1])
      .map(([p, d]) => [p, d[1]]).sort((a, b) => b[1] - a[1]);
    const W = 520, fila = 15, m = {l: 150, r: 48}, H = filas.length * fila + 8;
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Ranking bar chart'});
    const min = Math.min(0, ...filas.map((f) => f[1])), max = Math.max(0, ...filas.map((f) => f[1]));
    const x = (v) => m.l + (v - min) / ((max - min) || 1) * (W - m.l - m.r);
    filas.forEach(([p, v], i) => {
      const casa = D.home.includes(p);
      const yy = 4 + i * fila;
      svg.append(nodo('text', {x: m.l - 6, y: yy + 10, 'text-anchor': 'end', 'font-weight': casa ? 700 : 400,
        style: casa ? `fill:${COLOR[p]}` : ''}, D.countries[p]));
      svg.append(nodo('rect', {x: Math.min(x(0), x(v)), y: yy + 2, width: Math.max(1, Math.abs(x(v) - x(0))), height: fila - 4,
        fill: casa ? COLOR[p] : '#cfcbe0', rx: 2}));
      svg.append(nodo('text', {x: Math.max(x(0), x(v)) + 4, y: yy + 10}, numero(v)));
    });
    $('grafico-ranking').replaceChildren(svg);
    if (!filas.length) $('grafico-ranking').innerHTML = '<p class="nota">No data.</p>';
  }

  function mostrar() {
    const codigo = $('indicador').value;
    const ind = D.indicators.find((i) => i.code === codigo);
    $('ficha').textContent = `${ind.unit} · Source: ${ind.source} (code ${ind.code})`;
    lineas(codigo);
    ranking(codigo);
  }
  $('indicador').addEventListener('change', mostrar);
  mostrar();

  // coverage table for the three COIL countries
  const cob = {};
  for (const c of D.coverage) cob[c.iso3 + '|' + c.indicator] = c;
  const total = D.to - D.from + 1;
  $('cobertura').innerHTML = '<thead><tr><th>Indicator</th>' + D.home.map((p) => `<th>${esc(D.countries[p])}</th>`).join('')
    + '</tr></thead><tbody>' + D.indicators.map((i) => '<tr><td>' + esc(i.name) + '</td>' + D.home.map((p) => {
      const c = cob[p + '|' + i.code];
      const n = c ? c.years : 0;
      const clase = n === 0 ? 'vacio' : n < total * 0.75 ? 'parcial' : '';
      return `<td class="n ${clase}">${n === 0 ? 'no data' : `${n} yrs · to ${c.last}`}</td>`;
    }).join('') + '</tr>').join('') + '</tbody>';
})();
