// Renders the COIL website from content.js (editable text) and data/data.js (generated by datos/construir_datos.py).
(function () {
  const C = window.COIL_CONTENT;
  const D = window.COIL_DATA;
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'}[c]));
  const COLOR = {ESP: 'var(--esp)', SVK: 'var(--svk)', MNE: 'var(--mne)', EUU: 'var(--ue)'};
  const NS = 'http://www.w3.org/2000/svg';

  // ---------- Home ----------
  $('titulo').textContent = C.title;
  $('subtitulo').textContent = C.subtitle;
  $('curso').textContent = C.course;
  $('periodo').textContent = C.period;
  $('provisional').hidden = !C.provisional;
  $('universidades').innerHTML = C.universities.map((u) =>
    `<a class="uni" href="${esc(u.url)}" target="_blank" rel="noopener"><img src="${esc(u.logo)}" alt="${esc(u.name)}">`
    + `<strong>${esc(u.name)}</strong><span>${esc(u.country)}</span></a>`).join('');
  $('outcomes').innerHTML = C.outcomes.map((o) => `<li>${esc(o)}</li>`).join('');
  // Teaching team: photo if available (img/team/...), otherwise initials in the colour of the university
  const colorUni = {'University of Seville': 'var(--esp)', 'Technical University of Košice': 'var(--svk)', 'University of Montenegro': 'var(--mne)'};
  // first name + first surname (with two given names, the surname is the second-to-last word)
  const iniciales = (n) => { const w = n.trim().split(/\s+/); const s = w.length >= 4 ? w[w.length - 2] : (w[1] || ''); return (w[0][0] + (s[0] || '')).toUpperCase(); };
  $('teachers').innerHTML = C.teachers.map((t) => `<article class="docente" style="--color-uni:${colorUni[t.university] || 'var(--ulysseus)'}">
      ${t.photo ? `<img class="foto" src="${esc(t.photo)}" alt="${esc(t.name)}">`
        : `<div class="foto iniciales" style="background:${colorUni[t.university] || 'var(--ulysseus)'}" aria-hidden="true">${esc(iniciales(t.name))}</div>`}
      <h3>${esc(t.name)}</h3>
      <p class="uni-docente">${esc(t.university)}</p>
      ${t.role ? `<p class="nota">${esc(t.role)}</p>` : ''}
      ${t.email ? `<a href="mailto:${esc(t.email)}">${esc(t.email)}</a>` : ''}
    </article>`).join('');

  // ---------- Schedule ----------
  // Month calendars (Monday first); each COIL week is coloured by phase and can be clicked to see its details.
  const hoy = new Date(); hoy.setHours(0, 0, 0, 0);
  const fmt = (d) => d.toLocaleDateString('en-GB', {day: 'numeric', month: 'short'});
  const clave = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const fases = [...new Set(C.schedule.map((s) => s.phase))];
  const colorFase = (f) => `fase-${fases.indexOf(f) % 6}`;
  const semanaDe = new Map();  // 'yyyy-mm-dd' -> schedule entry
  for (const s of C.schedule) {
    const ini = new Date(s.start + 'T00:00:00');
    for (let i = 0; i < 7; i++) { const d = new Date(ini); d.setDate(ini.getDate() + i); semanaDe.set(clave(d), s); }
  }
  const primero = new Date(C.schedule[0].start + 'T00:00:00');
  const ultimo = new Date(C.schedule[C.schedule.length - 1].start + 'T00:00:00'); ultimo.setDate(ultimo.getDate() + 6);
  $('leyenda-fases').innerHTML = fases.map((f) => `<span><i class="${colorFase(f)}"></i>${esc(f)}</span>`).join('');
  let html = '';
  for (let m = new Date(primero.getFullYear(), primero.getMonth(), 1); m <= ultimo; m = new Date(m.getFullYear(), m.getMonth() + 1, 1)) {
    html += `<div class="mes"><h3>${m.toLocaleDateString('en-GB', {month: 'long', year: 'numeric'})}</h3><table><thead><tr>`
      + ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((d) => `<th>${d}</th>`).join('') + '</tr></thead><tbody><tr>';
    const desfase = (m.getDay() + 6) % 7;  // Monday = 0
    html += '<td class="fuera"></td>'.repeat(desfase);
    const dias = new Date(m.getFullYear(), m.getMonth() + 1, 0).getDate();
    for (let d = 1; d <= dias; d++) {
      const f = new Date(m.getFullYear(), m.getMonth(), d);
      const s = semanaDe.get(clave(f));
      const col = (desfase + d - 1) % 7;
      if (col === 0 && d > 1) html += '</tr><tr>';
      const clases = [s ? `coil ${colorFase(s.phase)}` : '', col >= 5 ? 'finde' : '', +f === +hoy ? 'hoy' : ''].join(' ').trim();
      html += `<td class="${clases}"${s ? ` data-week="${s.week}" title="Week ${s.week}: ${esc(s.title)}"` : ''}>`
        + `<span class="num">${d}</span>${s && col === 0 ? `<span class="etq">W${s.week}</span>` : ''}</td>`;
    }
    html += '<td class="fuera"></td>'.repeat((7 - (desfase + dias) % 7) % 7) + '</tr></tbody></table></div>';
  }
  $('calendario').innerHTML = html;

  // Deliverable due date: the Sunday of the same week
  const vence = (s) => { const d = new Date(s.start + 'T00:00:00'); d.setDate(d.getDate() + 6);
    return d.toLocaleDateString('en-GB', {weekday: 'long', day: 'numeric', month: 'long'}) + ', 23:59 CET'; };
  function fichaEntrega(s) {
    const e = s.deliverable;
    return `<div class="entrega"><p class="entrega-titulo">Deliverable: ${esc(e.name)}</p>
      <dl><dt>Due</dt><dd><strong>${esc(vence(s))}</strong></dd><dt>Who</dt><dd>${esc(e.who)}</dd>
      <dt>Format</dt><dd>${esc(e.format)}</dd><dt>Submit in</dt><dd>${esc(C.submission)}</dd></dl>
      <p class="entrega-sub">It must include:</p><ul>${e.include.map((i) => `<li>${esc(i)}</li>`).join('')}</ul></div>`;
  }

  function verSemana(n) {
    const s = C.schedule.find((x) => x.week === n);
    const ini = new Date(s.start + 'T00:00:00'); const fin = new Date(ini); fin.setDate(ini.getDate() + 6);
    document.querySelectorAll('#calendario td.coil').forEach((td) => td.classList.toggle('elegida', +td.dataset.week === n));
    $('detalle-semana').innerHTML = `<div class="cuando">Week ${s.week} · ${fmt(ini)} – ${fmt(fin)}</div>
      <span class="fase ${colorFase(s.phase)}">${esc(s.phase)}</span><h3>${esc(s.title)}</h3><p>${esc(s.activities)}</p>
      ${fichaEntrega(s)}
      <div class="nav-semana">${n > 1 ? `<button data-ir="${n - 1}">← Week ${n - 1}</button>` : '<span></span>'}
      ${n < C.schedule.length ? `<button data-ir="${n + 1}">Week ${n + 1} →</button>` : ''}</div>`;
  }
  $('calendario').addEventListener('click', (e) => { const td = e.target.closest('td.coil'); if (td) verSemana(+td.dataset.week); });
  $('detalle-semana').addEventListener('click', (e) => { const b = e.target.closest('button[data-ir]'); if (b) verSemana(+b.dataset.ir); });
  const enCurso = semanaDe.get(clave(hoy));
  verSemana(enCurso ? enCurso.week : (hoy < primero ? 1 : C.schedule.length));

  // ---------- Student guide ----------
  $('guia').innerHTML = (C.guide || []).map((g, i) => `<details class="tema"${i === 0 ? ' open' : ''}>
      <summary>${esc(g.title)}</summary>
      ${(g.text || []).map((p) => `<p>${esc(p)}</p>`).join('')}
      ${g.items ? `<ul>${g.items.map((it) => `<li>${esc(it)}</li>`).join('')}</ul>` : ''}
    </details>`).join('');
  $('tabla-entregas').innerHTML = '<thead><tr><th>Week</th><th>Due</th><th>Deliverable</th><th>Who</th><th>Format</th></tr></thead><tbody>'
    + C.schedule.map((s) => `<tr><td>${s.week}</td><td>${esc(vence(s).replace(', 23:59 CET', ''))}</td><td><strong>${esc(s.deliverable.name)}</strong></td>`
      + `<td>${esc(s.deliverable.who)}</td><td>${esc(s.deliverable.format)}</td></tr>`).join('') + '</tbody>';
  $('regla-entrega').innerHTML = `Every deliverable is due on <strong>${esc(C.deadline)}</strong> of its week and is submitted in ${esc(C.submission)}. Click on a week in the schedule to see exactly what it must include.`;
  const nombreInd = Object.fromEntries((window.COIL_DATA ? window.COIL_DATA.indicators : []).map((i) => [i.code, i.name]));
  $('ejemplos').innerHTML = C.examples.map((x) => `<article class="ejemplo"><h3>${esc(x.title)}</h3>
      <p class="pregunta">${esc(x.question)}</p>
      <p><b>Indicators:</b> ${x.indicators.map((k) => `${esc(nombreInd[k] || k)} <code>${esc(k)}</code>`).join(' · ')}</p>
      <p><b>Methods:</b> ${esc(x.methods)}</p></article>`).join('');
  $('plantillas').innerHTML = C.templates.map((t) => `<details class="tema"><summary>${esc(t.title)}</summary>
      <ul>${t.items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul></details>`).join('');
  $('beneficios').innerHTML = C.benefits.map((b) => `<article class="beneficio"><h3>${esc(b.title)}</h3><p>${esc(b.text)}</p></article>`).join('');

  // ---------- Home: what is due this week ----------
  {
    const s = enCurso || C.schedule.find((x) => new Date(x.start + 'T00:00:00') > hoy) || C.schedule[C.schedule.length - 1];
    const empezado = !!enCurso;
    $('esta-semana').innerHTML = `<p class="etiqueta">${empezado ? 'This week' : 'Coming up'} · Week ${s.week}: ${esc(s.title)}</p>
      <p class="esta-entrega">Deliverable: <strong>${esc(s.deliverable.name)}</strong> · ${esc(s.deliverable.who)} · due <strong>${esc(vence(s))}</strong></p>
      <p class="accesos"><a class="boton-pdf" href="#schedule">See the schedule</a> <a class="boton-sec" href="#guide">Read the student guide</a>
      <a class="boton-sec" href="#benefits">Why join?</a></p>`;
  }

  // ---------- One section at a time ----------
  const vistas = new Set([...document.querySelectorAll('.vista')].map((s) => s.dataset.vista));
  function mostrarVista() {
    const v = vistas.has(location.hash.slice(1)) ? location.hash.slice(1) : 'home';
    document.querySelectorAll('.vista').forEach((s) => { s.hidden = s.dataset.vista !== v; });
    document.querySelectorAll('nav a').forEach((l) => l.classList.toggle('activo', l.getAttribute('href') === '#' + v));
    window.scrollTo(0, 0);
  }
  window.addEventListener('hashchange', mostrarVista);
  mostrarVista();

  // ---------- Projects and resources ----------
  $('proyectos').innerHTML = C.projects.length
    ? C.projects.map((p) => `<article class="proyecto">${p.image ? `<img src="${esc(p.image)}" alt="">` : ''}
        <div><h3>${esc(p.team)}</h3><p class="nota">${esc((p.universities || []).join(' · '))}</p><p>${esc(p.topic)}</p>
        ${p.link ? `<a href="${esc(p.link)}" target="_blank" rel="noopener">Open dashboard</a>` : ''}</div></article>`).join('')
    : '<p class="vacio-proyectos">Team projects will be published here after the joint online presentation.</p>';
  $('recursos').innerHTML = C.resources.map((r) => `<li><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.title)}</a></li>`).join('');

  // ---------- Data ----------
  if (!D) { $('data').insertAdjacentHTML('beforeend', '<p class="nota">Data file not found: run datos/construir_datos.py.</p>'); return; }
  const paises = Object.keys(D.countries).filter((p) => p !== 'EUU');
  $('n-paises').textContent = paises.length;
  $('rango-anios').textContent = `${D.from}–${D.to}`;
  document.querySelectorAll('.rango-anios').forEach((e) => { e.textContent = `${D.from} and ${D.to}`; });
  $('actualizado').textContent = D.updated;

  const temas = [...new Set(D.indicators.map((i) => i.theme))];
  $('indicador').innerHTML = temas.map((t) => `<optgroup label="${esc(t)}">`
    + D.indicators.filter((i) => i.theme === t).map((i) => `<option value="${esc(i.code)}">${esc(i.name)}</option>`).join('')
    + '</optgroup>').join('');

  const nodo = (tag, attrs, texto) => {
    const n = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, v);
    if (texto !== undefined) n.textContent = texto;
    return n;
  };
  const numero = (v) => (Math.abs(v) >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : Math.abs(v) >= 1000 ? Math.round(v).toLocaleString('en-GB') : (+v.toFixed(1)).toString());

  function lineas(codigo) {
    const W = 520, H = 280, m = {l: 48, r: 12, t: 12, b: 28};
    const serie = D.series[codigo] || {};
    const claves = ['ESP', 'SVK', 'MNE', 'EUU'].filter((p) => serie[p]);
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Line chart'});
    const todos = claves.flatMap((p) => serie[p]);
    if (!todos.length) { $('grafico-lineas').innerHTML = '<p class="nota">No data for the three countries.</p>'; return; }
    const ys = todos.map((d) => d[1]);
    let y0 = Math.min(...ys), y1 = Math.max(...ys);
    if (y0 === y1) { y0 -= 1; y1 += 1; }
    const pad = (y1 - y0) * 0.08; y0 -= pad; y1 += pad;
    const x = (a) => m.l + (a - D.from) / (D.to - D.from) * (W - m.l - m.r);
    const y = (v) => H - m.b - (v - y0) / (y1 - y0) * (H - m.t - m.b);
    for (let k = 0; k <= 4; k++) {
      const v = y0 + (y1 - y0) * k / 4;
      svg.append(nodo('line', {x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), stroke: '#e3e1ea'}));
      svg.append(nodo('text', {x: m.l - 6, y: y(v) + 4, 'text-anchor': 'end'}, numero(v)));
    }
    for (let a = D.from; a <= D.to; a += 5) svg.append(nodo('text', {x: x(a), y: H - 8, 'text-anchor': 'middle'}, a));
    for (const p of claves) {
      const d = serie[p].map(([a, v], i) => `${i ? 'L' : 'M'}${x(a).toFixed(1)},${y(v).toFixed(1)}`).join('');
      svg.append(nodo('path', {d, fill: 'none', stroke: COLOR[p], 'stroke-width': p === 'EUU' ? 2 : 2.6,
        'stroke-dasharray': p === 'EUU' ? '5 4' : ''}));
      for (const [a, v] of serie[p]) {
        const c = nodo('circle', {cx: x(a), cy: y(v), r: 2.6, fill: COLOR[p]});
        c.append(nodo('title', {}, `${D.countries[p]}, ${a}: ${numero(v)}`));
        svg.append(c);
      }
    }
    const cont = $('grafico-lineas');
    cont.replaceChildren(svg);
    cont.insertAdjacentHTML('beforeend', '<div class="leyenda">' + ['ESP', 'SVK', 'MNE', 'EUU'].map((p) =>
      `<span><i style="background:${COLOR[p]}"></i>${esc(D.countries[p])}${serie[p] ? '' : ' (no data)'}</span>`).join('') + '</div>');
  }

  function ranking(codigo) {
    const serie = D.series[codigo] || {};
    // latest year with data for most countries
    const cuenta = {};
    for (const p of paises) for (const [a] of serie[p] || []) cuenta[a] = (cuenta[a] || 0) + 1;
    const anio = +Object.keys(cuenta).filter((a) => cuenta[a] >= paises.length * 0.6).sort().pop()
      || +Object.keys(cuenta).sort().pop();
    $('titulo-ranking').textContent = `All countries in ${anio || '—'}`;
    const filas = paises.map((p) => [p, (serie[p] || []).find((d) => d[0] === anio)]).filter((f) => f[1])
      .map(([p, d]) => [p, d[1]]).sort((a, b) => b[1] - a[1]);
    const W = 520, fila = 15, m = {l: 150, r: 48}, H = filas.length * fila + 8;
    const svg = nodo('svg', {viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': 'Ranking bar chart'});
    const min = Math.min(0, ...filas.map((f) => f[1])), max = Math.max(0, ...filas.map((f) => f[1]));
    const x = (v) => m.l + (v - min) / ((max - min) || 1) * (W - m.l - m.r);
    filas.forEach(([p, v], i) => {
      const casa = D.home.includes(p);
      const yy = 4 + i * fila;
      svg.append(nodo('text', {x: m.l - 6, y: yy + 10, 'text-anchor': 'end', 'font-weight': casa ? 700 : 400,
        style: casa ? `fill:${COLOR[p]}` : ''}, D.countries[p]));
      svg.append(nodo('rect', {x: Math.min(x(0), x(v)), y: yy + 2, width: Math.max(1, Math.abs(x(v) - x(0))), height: fila - 4,
        fill: casa ? COLOR[p] : '#cfcbe0', rx: 2}));
      svg.append(nodo('text', {x: Math.max(x(0), x(v)) + 4, y: yy + 10}, numero(v)));
    });
    $('grafico-ranking').replaceChildren(svg);
    if (!filas.length) $('grafico-ranking').innerHTML = '<p class="nota">No data.</p>';
  }

  function mostrar() {
    const codigo = $('indicador').value;
    const ind = D.indicators.find((i) => i.code === codigo);
    $('ficha').textContent = `${ind.unit} · Source: ${ind.source} (code ${ind.code})`;
    lineas(codigo);
    ranking(codigo);
  }
  $('indicador').addEventListener('change', mostrar);
  mostrar();

  // coverage table for the three COIL countries
  const cob = {};
  for (const c of D.coverage) cob[c.iso3 + '|' + c.indicator] = c;
  const total = D.to - D.from + 1;
  $('cobertura').innerHTML = '<thead><tr><th>Indicator</th>' + D.home.map((p) => `<th>${esc(D.countries[p])}</th>`).join('')
    + '</tr></thead><tbody>' + D.indicators.map((i) => '<tr><td>' + esc(i.name) + '</td>' + D.home.map((p) => {
      const c = cob[p + '|' + i.code];
      const n = c ? c.years : 0;
      const clase = n === 0 ? 'vacio' : n < total * 0.75 ? 'parcial' : '';
      return `<td class="n ${clase}">${n === 0 ? 'no data' : `${n} yrs · to ${c.last}`}</td>`;
    }).join('') + '</tr>').join('') + '</tbody>';
})();
