// Editable content of the COIL website. Teachers can change anything here without touching the rest of the code.
// Dates are provisional until confirmed by the three universities.

window.COIL_CONTENT = {
  title: 'Comparing Europe with Data',
  subtitle: 'A Ulysseus COIL on comparative socio-economic data analysis',
  course: 'Advanced Data Analysis and Visualization (3 ECTS)',
  period: '12 October – 11 December 2026',
  provisional: true,

  universities: [
    {name: 'University of Seville', country: 'Spain', logo: 'img/us.svg', url: 'https://www.us.es'},
    {name: 'Technical University of Košice', country: 'Slovakia', logo: 'img/tuke.svg', url: 'https://www.tuke.sk'},
    {name: 'University of Montenegro', country: 'Montenegro', logo: 'img/uom.svg', url: 'https://www.ucg.ac.me'},
  ],

  // Teaching team: {name, university, email, photo: 'img/team/file.jpg' (optional), role (optional)}
  teachers: [
    {name: 'Daniel Ruiz Romera', university: 'University of Seville', email: 'druiz8@us.es', photo: 'img/team/daniel-ruiz-romera.jpg'},
    {name: 'Alena Mojsejová', university: 'Technical University of Košice', email: 'alena.mojsejova@tuke.sk', photo: 'img/team/alena-mojsejova.jpg'},
    {name: 'Bojan Pejović', university: 'University of Montenegro', email: 'bojan.p@ucg.ac.me', photo: 'img/team/bojan-pejovic.jpg'},
    {name: 'Dana Paľová', university: 'Technical University of Košice', email: 'dana.palova@tuke.sk', photo: 'img/team/dana-palova.jpg'},
    {name: 'Víctor Ernesto Pérez León', university: 'University of Seville', email: 'vpleon@us.es', photo: 'img/team/victor-perez-leon.jpg'},
  ],

  outcomes: [
    'Collaborate effectively in virtual international teams.',
    'Compare economic and social phenomena across different national contexts.',
    'Communicate analytical findings to international audiences in English.',
    'Apply data analysis techniques to datasets from different countries.',
    'Reflect on how cultural and institutional differences influence data interpretation.',
  ],

  // One entry per week (Monday date). phase groups the weeks; deliverable is what teams hand in.
  schedule: [
    {week: 1, start: '2026-10-12', phase: 'Orientation', title: 'Kick-off and intercultural orientation',
      activities: 'Joint online welcome session. Introductions and icebreaker in mixed groups. How the COIL works.',
      deliverable: 'Personal profile and first reflection (expectations).'},
    {week: 2, start: '2026-10-19', phase: 'Orientation', title: 'International teams and topic selection',
      activities: 'Teams with students from the three universities. Agree on working rules, tools and meeting times. Choose a socio-economic or public-policy question.',
      deliverable: 'Team charter and one-page topic proposal (question, countries, indicators).'},
    {week: 3, start: '2026-10-26', phase: 'Data', title: 'Data collection and preparation',
      activities: 'Start from the COIL dataset; add national sources if needed. Document every variable.',
      deliverable: 'Clean dataset and data dictionary.'},
    {week: 4, start: '2026-11-02', phase: 'Data', title: 'Exploratory data analysis',
      activities: 'Descriptive statistics, distributions, missing values, first visual comparisons of Spain, Slovakia and Montenegro within Europe.',
      deliverable: 'EDA notebook (Python or R).'},
    {week: 5, start: '2026-11-09', phase: 'Methods', title: 'Regression and classification',
      activities: 'Relationships between indicators across European countries and over time, and simple classification models. Interpreting results in different institutional contexts.',
      deliverable: 'Results notebook and mid-term reflection (team work and intercultural collaboration).'},
    {week: 6, start: '2026-11-16', phase: 'Methods', title: 'Dimensionality reduction and clustering',
      activities: 'Principal component analysis and clustering of countries: which European countries look alike, and where do Spain, Slovakia and Montenegro fall?',
      deliverable: 'Analysis notebook with results.'},
    {week: 7, start: '2026-11-23', phase: 'Communication', title: 'Dashboards and data storytelling',
      activities: 'Design the dashboard for a non-specialist audience. Peer feedback between teams.',
      deliverable: 'Dashboard draft.'},
    {week: 8, start: '2026-11-30', phase: 'Communication', title: 'Final dashboard and rehearsal',
      activities: 'Incorporate feedback, prepare the presentation, rehearse online.',
      deliverable: 'Final dashboard (link or PDF) and slides.'},
    {week: 9, start: '2026-12-07', phase: 'Presentation', title: 'Joint online presentation and reflection',
      activities: 'All teams present to students and teachers from the three universities. Closing discussion.',
      deliverable: 'Final individual reflection.'},
  ],

  // Student guide: one block per topic. text = paragraphs; items = bullet points (both optional).
  guide: [
    {title: 'What is this COIL and what will you do?',
      text: ['A COIL (Collaborative Online International Learning) connects your course with courses at two partner universities of the Ulysseus alliance. For nine weeks you will work online in an international team with students from Seville, Košice and Podgorica.',
        'Together you will choose a socio-economic question, analyse real data from European countries with the methods of the course, build a dashboard and present your results to everybody in a joint online session. The COIL is part of your own course: you receive credits and are graded by your home university.']},
    {title: 'Before you start: checklist',
      items: ['Read this guide and the schedule.',
        'Make sure you can use Python or R, and Power BI if your course uses it.',
        'Download the COIL dataset from the Data section and open it once.',
        'Check that you can join online meetings with camera and microphone (your teachers will tell you which platform to use).',
        'Prepare a short personal profile: who you are, what you study, what you are good at and what you want to learn.']},
    {title: 'Working in an international team',
      text: ['Spain, Slovakia and Montenegro are in the same time zone (CET), so scheduling meetings is easy. Cultural and academic habits may differ, and that is part of the learning.'],
      items: ['Agree on one main communication channel and answer messages within 48 hours on working days.',
        'Meet online at least once a week and write down what was decided and who does what.',
        'Use English in all team communication, so that nobody is left out.',
        'Rotate roles every two or three weeks: coordinator, data lead, analyst, visualisation lead and editor.',
        'Write a team charter in week 2: goals, roles, deadlines, how you take decisions and what you do if someone does not contribute.',
        'If a problem in the team cannot be solved within the team, tell your teacher early.']},
    {title: 'The project step by step',
      items: ['Weeks 1–2: get to know each other, form teams and choose a question that can be answered with data from several countries.',
        'Weeks 3–4: prepare the data and explore it. Document every variable and every change you make.',
        'Weeks 5–6: apply the methods of the course (regression, classification, dimensionality reduction and clustering) and interpret the results in each national context.',
        'Weeks 7–8: turn your results into a clear dashboard for a non-specialist audience and give feedback to another team.',
        'Week 9: present to students and teachers of the three universities and write your final reflection.']},
    {title: 'Using the data',
      items: ['Start from the COIL dataset; you may add other sources if you document them.',
        'Always cite the source of each indicator (World Bank, IMF, Eurostat…).',
        'Some indicators have gaps, especially for Montenegro. Do not fill them in silently: either leave them out or explain clearly what you did.',
        'Check units and years before comparing countries.',
        'Correlation is not causation: be careful with your conclusions.']},
    {title: 'Deliverables and assessment',
      text: ['There is one deliverable each week (see the schedule). Each university grades its own students.',
        'The COIL gives you additional points on top of your course grade: up to 1 extra point (out of 10) at the University of Seville, and up to 10 extra points (out of 100) at the Technical University of Košice and the University of Montenegro. Your teachers will explain how these points are awarded.'],
      items: ['Submit deliverables on time through the channel indicated by your teacher.',
        'Final dashboard: an interactive link, or a PDF or screenshots if Power BI publishing is not allowed in your university account.',
        'The final team projects will be shown in the Projects section of this website (team name and topic only, no personal data).']},
    {title: 'Reflection',
      text: ['You will write a short reflection at the start, in the middle and at the end of the COIL. Some questions to guide you:'],
      items: ['What did you expect from working with students from other countries, and what actually happened?',
        'How did cultural or institutional differences change the way your team read the data?',
        'What would you do differently in an international team next time?',
        'Which skill (technical or personal) improved the most?']},
    {title: 'Academic integrity and AI tools',
      items: ["Your work must be your own and your team's. Cite all sources, data and code you reuse.",
        'Follow the rules of your home university on the use of AI tools, and say clearly when and how you used them.',
        'Every team member must be able to explain the analysis and the results.']},
    {title: 'Questions and contact',
      text: ['For anything about grades, deadlines or your course, contact your teacher at your home university (see the Teaching team section). For questions about the joint activities or the dataset, any teacher of the COIL can help you.']},
  ],

  // Team projects, added by the teachers after each team submits its link.
  // {team, universities: ['US','TUKE','UoM'], topic, link, image}
  projects: [],

  resources: [
    {title: 'Ulysseus COIL Handbook: A Practical Guide for Educators',
      url: 'https://ulysseus.eu/wp-content/uploads/2025/02/Ulysseus-COIL-Handbook-for-teachers-1.pdf'},
    {title: 'World Bank Open Data (source of most indicators)', url: 'https://data.worldbank.org'},
    {title: 'IMF DataMapper (government debt)', url: 'https://www.imf.org/external/datamapper'},
    {title: 'Eurostat database (more European indicators)', url: 'https://ec.europa.eu/eurostat/data/database'},
  ],
};
