// Editable content of the COIL website. Teachers can change anything here without touching the rest of the code.
// Dates are provisional until confirmed by the three universities.

window.COIL_CONTENT = {
  title: 'Comparing Europe with Data',
  subtitle: 'A Ulysseus COIL on comparative socio-economic data analysis',
  course: 'Advanced Data Analysis and Visualization (3 ECTS)',
  period: '12 October – 11 December 2026',
  provisional: true,

  universities: [
    {name: 'University of Seville', country: 'Spain', logo: 'img/us.svg', url: 'https://www.us.es'},
    {name: 'Technical University of Košice', country: 'Slovakia', logo: 'img/tuke.svg', url: 'https://www.tuke.sk'},
    {name: 'University of Montenegro', country: 'Montenegro', logo: 'img/uom.svg', url: 'https://www.ucg.ac.me'},
  ],

  teamIntro: 'The COIL is designed and run jointly by teachers from the three universities. We share the schedule, the dataset and the final presentation, and each of us guides and grades the students of our own university.',
  teamWork: [
    'Week 1: joint online welcome session with all teachers and students.',
    'During the COIL: your home teacher follows your progress, answers your questions and grades your deliverables.',
    'Week 9: all teachers attend the joint online presentation and give feedback to every team.',
    'At the end: the teachers coordinate the extra points and the certificates of participation.',
  ],

  // Teaching team: {name, university, email, photo: 'img/team/file.jpg', bio: one sentence (optional)}
  teachers: [
    {name: 'Daniel Ruiz Romera', university: 'University of Seville', email: 'druiz8@us.es', bio: 'Department of Applied Economics II. Teaches econometrics; works on innovation policy, entrepreneurship and academic spin-offs, and EU funding for firms.', photo: 'img/team/daniel-ruiz-romera.jpg'},
    {name: 'Alena Mojsejová', university: 'Technical University of Košice', email: 'alena.mojsejova@tuke.sk', bio: 'Department of Applied Mathematics and Business Informatics, Faculty of Economics. Teaches probability, statistics and social statistics; works on income inequality and gender gaps.', photo: 'img/team/alena-mojsejova.jpg'},
    {name: 'Bojan Pejović', university: 'University of Montenegro', email: 'bojan.p@ucg.ac.me', bio: 'Faculty of Economics. Head of the Center for Statistical Analysis; teaches statistics and econometrics. PhD in Economics (University of Belgrade).', photo: 'img/team/bojan-pejovic.jpg'},
    {name: 'Dana Paľová', university: 'Technical University of Košice', email: 'dana.palova@tuke.sk', bio: 'Department of Applied Mathematics and Business Informatics, Faculty of Economics. Teaches data analysis and visualisation, business informatics and AI in business; works on business intelligence, digital transformation and e-learning.', photo: 'img/team/dana-palova.jpg'},
    {name: 'Víctor Ernesto Pérez León', university: 'University of Seville', email: 'vpleon@us.es', bio: 'Department of Applied Economics II. Teaches econometrics and statistics for business; works on composite indicators, multicriteria analysis and sustainable tourism.', photo: 'img/team/victor-perez-leon.jpg'},
  ],

  outcomes: [
    'Collaborate effectively in virtual international teams.',
    'Compare economic and social phenomena across different national contexts.',
    'Communicate analytical findings to international audiences in English.',
    'Apply data analysis techniques to datasets from different countries.',
    'Reflect on how cultural and institutional differences influence data interpretation.',
  ],

  // Submission rules that apply to every week
  deadline: 'Sunday, 23:59 CET',
  submission: 'the COIL team on Microsoft Teams (one assignment per deliverable)',

  // One entry per week (Monday date). Only weeks 2, 6 and 9 have a deliverable, due on the Sunday of that week.
  // Weeks without a deliverable show "goal": what the team should have ready by the end of the week.
  schedule: [
    {week: 1, start: '2026-10-12', phase: 'Orientation', title: 'Kick-off and intercultural orientation',
      activities: 'Joint online welcome session. Introductions and icebreaker in mixed groups. How the COIL works.',
      goal: 'Join the COIL team on Microsoft Teams and introduce yourself in the general channel (who you are, what you study, what you want to learn).'},
    {week: 2, start: '2026-10-19', phase: 'Orientation', title: 'International teams and topic selection',
      activities: 'Teams with students from the three universities. Agree on working rules, tools and meeting times. Choose a socio-economic or public-policy question.',
      deliverable: {number: 1, name: 'Team charter and topic proposal', who: 'Team', format: 'One PDF, maximum 2 pages (use the templates in the guide)',
        include: ['Team charter: team name, members and universities, roles, communication channel, weekly meeting time, how you take decisions, what you do if someone does not contribute.',
          'Topic proposal: research question, why it matters for Spain, Slovakia and Montenegro, 3–6 indicators from the COIL dataset (with their codes), countries and years, and the methods you expect to use.']}},
    {week: 3, start: '2026-10-26', phase: 'Data', title: 'Data collection and preparation',
      activities: 'Start from the COIL dataset; add national sources if needed. Document every variable.',
      goal: 'Your dataset is ready (one row per country and year) and every variable is documented in a data dictionary.'},
    {week: 4, start: '2026-11-02', phase: 'Data', title: 'Exploratory data analysis',
      activities: 'Descriptive statistics, distributions, missing values, first visual comparisons of Spain, Slovakia and Montenegro within Europe.',
      goal: 'Descriptive statistics and first charts are done, and the team agrees on what the data show.'},
    {week: 5, start: '2026-11-09', phase: 'Methods', title: 'Regression and classification',
      activities: 'Relationships between indicators across European countries and over time, and simple classification models. Interpreting results in different institutional contexts.',
      goal: 'Your regression or classification model is estimated and interpreted.'},
    {week: 6, start: '2026-11-16', phase: 'Methods', title: 'Dimensionality reduction and clustering',
      activities: 'Principal component analysis and clustering of countries: which European countries look alike, and where do Spain, Slovakia and Montenegro fall?',
      deliverable: {number: 2, name: 'Analysis notebook', who: 'Team', format: 'Python or R notebook (.ipynb, .Rmd or Quarto), or Gretl script (.inp) with its output, + exported HTML or PDF + your dataset (CSV or Excel)',
        include: ['Data: the dataset you analysed and a data dictionary (name, code, definition, unit, source and years of every variable), with missing values and how you handled them.',
          'Exploratory analysis: descriptive statistics and at least three charts, one comparing Spain, Slovakia and Montenegro with the rest of Europe.',
          'Regression or classification: model specification, results table and interpretation in plain English.',
          'PCA and clustering: variance explained, number of clusters and why, and where Spain, Slovakia and Montenegro fall.',
          'Limitations (sample size, missing data, causality) and your three main conclusions.']}},
    {week: 7, start: '2026-11-23', phase: 'Communication', title: 'Dashboards and data storytelling',
      activities: 'Design the dashboard for a non-specialist audience. Give and receive feedback with another team.',
      goal: 'A first version of your dashboard, shown to another team for feedback.'},
    {week: 8, start: '2026-11-30', phase: 'Communication', title: 'Final dashboard and rehearsal',
      activities: 'Incorporate feedback, prepare the presentation, rehearse online.',
      goal: 'Final dashboard and slides ready; the presentation has been rehearsed.'},
    {week: 9, start: '2026-12-07', phase: 'Presentation', title: 'Joint online presentation and reflection',
      activities: 'All teams present to students and teachers from the three universities. Closing discussion.',
      deliverable: {number: 3, name: 'Final dashboard, presentation and final reflection', who: 'Team (dashboard, slides and presentation) + individual (reflection)',
        format: 'Dashboard link or PDF + slides (maximum 10 slides, 10 minutes) + one-page PDF reflection',
        note: 'Upload the dashboard and the slides before the joint presentation. The reflection is due on Sunday.',
        include: ['Final dashboard: your question, the data, three key findings and limitations, for a non-specialist audience.',
          'Slides and live presentation in the joint online session: every team member presents a part. This is required to receive the extra points.',
          'Final individual reflection (300–400 words): what did you learn about data analysis, about working internationally and about yourself?']}},
  ],

  // Why join: shown on the home page and in the PDF
  benefits: [
    {title: 'Extra points on your grade', text: 'Up to 1 extra point (out of 10) at the University of Seville, and up to 10 extra points (out of 100) at the Technical University of Košice and the University of Montenegro, for students who complete the final presentation.'},
    {title: 'Certificate of participation', text: 'Students who complete the COIL receive a certificate of participation in a Ulysseus European University COIL, which you can add to your CV and LinkedIn.'},
    {title: 'An international experience without travelling', text: 'Work for nine weeks with students from Spain, Slovakia and Montenegro, from your own classroom.'},
    {title: 'A real project for your portfolio', text: 'You will analyse real European data and build a dashboard you can show to future employers. The best projects are published on this website.'},
    {title: 'Skills employers ask for', text: 'Data analysis with Python, R or Gretl, dashboards, teamwork in international and online teams, and presenting in English.'},
    {title: 'A head start for your final project', text: 'You can develop your COIL project further in your bachelor\'s thesis (Trabajo Fin de Grado or equivalent), in agreement with your supervisor: you will already have the question, the data and the first analyses.'},
    {title: 'A step towards international internships', text: 'An international project, teamwork in English and contacts in three countries are a strong point when you apply for internships abroad, such as Erasmus+ traineeships.'},
    {title: 'Your Ulysseus network', text: 'Meet students and teachers from other Ulysseus universities: a first step towards an Erasmus exchange or further European projects.'},
  ],

  // Example projects: ideas that work with the COIL dataset (teams may propose their own)
  examples: [
    {title: 'Education and youth unemployment', question: 'Do countries with more young people in higher education have lower youth unemployment?',
      indicators: ['SL.UEM.1524.ZS', 'SE.TER.ENRR', 'NY.GDP.PCAP.PP.KD'], methods: 'Regression on the country panel; compare Spain, Slovakia and Montenegro with the European pattern.'},
    {title: 'The digital divide in Europe', question: 'Which European countries are digital leaders and which are lagging behind, and does it depend on income?',
      indicators: ['IT.NET.USER.ZS', 'IT.NET.BBND.P2', 'NY.GDP.PCAP.PP.KD'], methods: 'Correlation, then clustering of countries by their digital profile.'},
    {title: 'Ageing and public spending', question: 'Do older societies spend more on health, and do they have more public debt?',
      indicators: ['SP.POP.65UP.TO.ZS', 'SH.XPD.CHEX.GD.ZS', 'GGXWDG_NGDP'], methods: 'Regression with time trends; discuss differences in welfare systems.'},
    {title: 'Women in the labour market', question: 'Is higher female participation in the labour market linked to fertility and income across Europe?',
      indicators: ['SL.TLF.CACT.FE.ZS', 'SP.DYN.TFRT.IN', 'NY.GDP.PCAP.PP.KD'], methods: 'Regression and classification of countries into high and low participation groups.'},
    {title: 'The green transition', question: 'Are richer countries greener? Renewable energy and income in Europe.',
      indicators: ['EG.FEC.RNEW.ZS', 'NY.GDP.PCAP.PP.KD', 'EN.GHG.CO2.PC.CE.AR5'], methods: 'Regression and clustering. Note: there are no CO2 data for Montenegro, so explain how you deal with it.'},
    {title: 'Inequality and the structure of the economy', question: 'Are economies with a larger service sector more or less unequal?',
      indicators: ['SI.POV.GINI', 'NV.SRV.TOTL.ZS', 'NY.GDP.MKTP.KD.ZG'], methods: 'PCA to summarise the economic structure, then clustering.'},
  ],

  // Templates referred to in the weekly deliverables
  templates: [
    {title: 'Template: topic proposal (week 2)', items: ['Team name and members (name, university).', 'Research question (one sentence, ending with a question mark).',
      'Why it matters for Spain, Slovakia and Montenegro (3–4 sentences).', 'Indicators: name and code of 3–6 indicators from the COIL dataset.',
      'Countries and years you will use.', 'Methods you expect to use.', 'Possible problems (missing data, comparability) and how you will handle them.']},
    {title: 'Template: team charter (week 2)', items: ['Our goal as a team.', 'Roles for the first weeks (coordinator, data lead, analyst, visualisation lead, editor) and when we will rotate them.',
      'Communication channel and maximum answer time.', 'Weekly meeting day and time (CET).', 'How we take decisions.', 'What we do if a member does not contribute or misses a deadline.']},
    {title: 'Template: data dictionary (week 3)', items: ['One row per variable with these columns: variable name · indicator code · definition · unit · source · years covered · missing values and how they were handled.']},
  ],

  // Student guide: one block per topic. text = paragraphs; items = bullet points (both optional).
  guide: [
    {title: 'What is this COIL and what will you do?',
      text: ['A COIL (Collaborative Online International Learning) connects your course with courses at two partner universities of the Ulysseus alliance. For nine weeks you will work online in an international team with students from Seville, Košice and Podgorica.',
        'Together you will choose a socio-economic question, analyse real data from European countries with the methods of the course, build a dashboard and present your results to everybody in a joint online session. The COIL is part of your own course: you receive credits and are graded by your home university.']},
    {title: 'Before you start: checklist',
      items: ['Read this guide and the schedule.',
        'Make sure you can use Python, R or Gretl, and Power BI if your course uses it.',
        'Download the COIL dataset from the Data section and open it once.',
        'Join the COIL team on Microsoft Teams (you will receive an invitation) and check that your camera and microphone work.',
        'In week 1, introduce yourself in the general channel of the COIL team on Microsoft Teams.']},
    {title: 'Working in an international team',
      text: ['Spain, Slovakia and Montenegro are in the same time zone (CET), so scheduling meetings is easy. Cultural and academic habits may differ, and that is part of the learning.'],
      items: ['Agree on one main communication channel and answer messages within 48 hours on working days.',
        'Meet online at least once a week and write down what was decided and who does what.',
        'Use English in all team communication, so that nobody is left out.',
        'Rotate roles every two or three weeks: coordinator, data lead, analyst, visualisation lead and editor.',
        'Write a team charter in week 2: goals, roles, deadlines, how you take decisions and what you do if someone does not contribute.',
        'If a problem in the team cannot be solved within the team, tell your teacher early.']},
    {title: 'The project step by step',
      items: ['Weeks 1–2: get to know each other, form teams and choose a question that can be answered with data from several countries (deliverable 1).',
        'Weeks 3–4: prepare the data and explore it. Document every variable and every change you make.',
        'Weeks 5–6: apply the methods of the course (regression, classification, dimensionality reduction and clustering) and interpret the results in each national context (deliverable 2).',
        'Weeks 7–8: turn your results into a clear dashboard for a non-specialist audience and give feedback to another team.',
        'Week 9: present to students and teachers of the three universities and write your final reflection (deliverable 3).']},
    {title: 'Using the data',
      items: ['Start from the COIL dataset; you may add other sources if you document them.',
        'Always cite the source of each indicator (World Bank, IMF, Eurostat…).',
        'Some indicators have gaps, especially for Montenegro. Do not fill them in silently: either leave them out or explain clearly what you did.',
        'Check units and years before comparing countries.',
        'Correlation is not causation: be careful with your conclusions.']},
    {title: 'Deliverables and assessment',
      text: ['There are three deliverables: in week 2, week 6 and week 9 (see the table above and the schedule). Each university grades its own students.',
        'The COIL gives you additional points on top of your course grade: up to 1 extra point (out of 10) at the University of Seville, and up to 10 extra points (out of 100) at the Technical University of Košice and the University of Montenegro. The extra points are awarded to students who complete the final presentation of the project in week 9.'],
      items: ['Each deliverable is due on Sunday at 23:59 CET of its week and is submitted in the COIL team on Microsoft Teams.',
        'If you cannot meet a deadline, tell your team and your teacher before the deadline, not after.',
        'Final dashboard: an interactive link, or a PDF or screenshots if Power BI publishing is not allowed in your university account.',
        'The final team projects will be shown in the Projects section of this website (team name and topic only, no personal data).']},
    {title: 'Reflection',
      text: ['At the end of the COIL you will write a short individual reflection (part of deliverable 3). Keep some notes along the way. Some questions to guide you:'],
      items: ['What did you expect from working with students from other countries, and what actually happened?',
        'How did cultural or institutional differences change the way your team read the data?',
        'What would you do differently in an international team next time?',
        'Which skill (technical or personal) improved the most?']},
    {title: 'Academic integrity and AI tools',
      items: ["Your work must be your own and your team's. Cite all sources, data and code you reuse.",
        'Follow the rules of your home university on the use of AI tools, and say clearly when and how you used them.',
        'Every team member must be able to explain the analysis and the results.']},
    {title: 'Questions and contact',
      text: ['For anything about grades, deadlines or your course, contact your teacher at your home university (see the Teaching team section). For questions about the joint activities or the dataset, any teacher of the COIL can help you.']},
  ],

  // Team projects, added by the teachers after each team submits its link.
  // {team, universities: ['US','TUKE','UoM'], topic, link, image}
  projects: [],

  resources: [
    {title: 'Ulysseus COIL Handbook: A Practical Guide for Educators',
      url: 'https://ulysseus.eu/wp-content/uploads/2025/02/Ulysseus-COIL-Handbook-for-teachers-1.pdf'},
    {title: 'World Bank Open Data (source of most indicators)', url: 'https://data.worldbank.org'},
    {title: 'IMF DataMapper (government debt)', url: 'https://www.imf.org/external/datamapper'},
    {title: 'Eurostat database (more European indicators)', url: 'https://ec.europa.eu/eurostat/data/database'},
  ],
};
