// Editable content of the COIL website. Teachers can change anything here without touching the rest of the code.
// Dates are provisional until confirmed by the three universities.

window.COIL_CONTENT = {
  title: 'Comparing Europe with Data',
  subtitle: 'A Ulysseus COIL on comparative socio-economic data analysis',
  course: 'Advanced Data Analysis and Visualization (3 ECTS)',
  period: '12 October – 11 December 2026',
  provisional: true,

  universities: [
    {name: 'University of Seville', country: 'Spain', logo: 'img/us.svg', url: 'https://www.us.es'},
    {name: 'Technical University of Košice', country: 'Slovakia', logo: 'img/tuke.svg', url: 'https://www.tuke.sk'},
    {name: 'University of Montenegro', country: 'Montenegro', logo: 'img/uom.svg', url: 'https://www.ucg.ac.me'},
  ],

  // Teaching team: {name, university, email, photo: 'img/team/file.jpg' (optional), role (optional)}
  teachers: [
    {name: 'Daniel Ruiz Romera', university: 'University of Seville', email: 'druiz8@us.es', photo: 'img/team/daniel-ruiz-romera.jpg'},
    {name: 'Alena Mojsejová', university: 'Technical University of Košice', email: 'alena.mojsejova@tuke.sk', photo: 'img/team/alena-mojsejova.jpg'},
    {name: 'Bojan Pejović', university: 'University of Montenegro', email: 'bojan.p@ucg.ac.me', photo: 'img/team/bojan-pejovic.jpg'},
    {name: 'Dana Paľová', university: 'Technical University of Košice', email: 'dana.palova@tuke.sk', photo: 'img/team/dana-palova.jpg'},
    {name: 'Víctor Ernesto Pérez León', university: 'University of Seville', email: 'vpleon@us.es', photo: 'img/team/victor-perez-leon.jpg'},
  ],

  outcomes: [
    'Collaborate effectively in virtual international teams.',
    'Compare economic and social phenomena across different national contexts.',
    'Communicate analytical findings to international audiences in English.',
    'Apply data analysis techniques to datasets from different countries.',
    'Reflect on how cultural and institutional differences influence data interpretation.',
  ],

  // Submission rules that apply to every week
  deadline: 'Sunday, 23:59 CET',
  submission: 'the COIL team on Microsoft Teams (one assignment per week)',

  // One entry per week (Monday date). The deliverable is due on the Sunday of the same week (see deadline).
  schedule: [
    {week: 1, start: '2026-10-12', phase: 'Orientation', title: 'Kick-off and intercultural orientation',
      activities: 'Joint online welcome session. Introductions and icebreaker in mixed groups. How the COIL works.',
      deliverable: {name: 'Personal profile and first reflection', who: 'Individual', format: 'One-page PDF',
        include: ['Your name, university and degree programme.',
          'Your skills: tools you know (Python, R, Excel, Power BI…), languages and anything you are good at.',
          'What you want to learn in this COIL.',
          'First reflection (150–200 words): what do you expect from working with students from other countries? Any concerns?']}},
    {week: 2, start: '2026-10-19', phase: 'Orientation', title: 'International teams and topic selection',
      activities: 'Teams with students from the three universities. Agree on working rules, tools and meeting times. Choose a socio-economic or public-policy question.',
      deliverable: {name: 'Team charter and topic proposal', who: 'Team', format: 'One PDF, maximum 2 pages (use the templates in the guide)',
        include: ['Team charter: team name, members and universities, roles, communication channel, weekly meeting time, how you take decisions, what you do if someone does not contribute.',
          'Topic proposal: research question, why it matters for Spain, Slovakia and Montenegro, 3–6 indicators from the COIL dataset (with their codes), countries and years, and the methods you expect to use.']}},
    {week: 3, start: '2026-10-26', phase: 'Data', title: 'Data collection and preparation',
      activities: 'Start from the COIL dataset; add national sources if needed. Document every variable.',
      deliverable: {name: 'Clean dataset and data dictionary', who: 'Team', format: 'CSV or Excel file + data dictionary (PDF or a second sheet)',
        include: ['The dataset you will analyse: one row per country and year, one column per variable.',
          'Data dictionary: for every variable, its name, code, definition, unit, source and years covered.',
          'Missing values: which ones, and how you handled them (never fill them in silently).',
          'A short list of every change you made to the original data.']}},
    {week: 4, start: '2026-11-02', phase: 'Data', title: 'Exploratory data analysis',
      activities: 'Descriptive statistics, distributions, missing values, first visual comparisons of Spain, Slovakia and Montenegro within Europe.',
      deliverable: {name: 'Exploratory analysis notebook', who: 'Team', format: 'Notebook (.ipynb, .Rmd or Quarto) + exported HTML or PDF',
        include: ['Table of descriptive statistics for your variables.',
          'At least three charts, one of them comparing Spain, Slovakia and Montenegro with the rest of Europe.',
          'Summary of missing values.',
          'Three written observations about what the data show, and your next steps.']}},
    {week: 5, start: '2026-11-09', phase: 'Methods', title: 'Regression and classification',
      activities: 'Relationships between indicators across European countries and over time, and simple classification models. Interpreting results in different institutional contexts.',
      deliverable: {name: 'Results notebook and mid-term reflection', who: 'Team (notebook) + individual (reflection)', format: 'Notebook + exported HTML or PDF; reflection as a one-page PDF',
        include: ['Model specification: dependent and explanatory variables, and why you chose them.',
          'Results table and an interpretation in plain English.',
          'Limitations of the model (sample size, missing data, causality).',
          'Individual mid-term reflection (250–300 words): how is the team working, and what have you learned from your teammates?']}},
    {week: 6, start: '2026-11-16', phase: 'Methods', title: 'Dimensionality reduction and clustering',
      activities: 'Principal component analysis and clustering of countries: which European countries look alike, and where do Spain, Slovakia and Montenegro fall?',
      deliverable: {name: 'Clustering notebook', who: 'Team', format: 'Notebook + exported HTML or PDF',
        include: ['Variables used and how you standardised them.',
          'Principal components: variance explained and what each component means.',
          'Clusters: method, number of clusters and why.',
          'Which countries fall in each cluster, and where Spain, Slovakia and Montenegro are.',
          'Three conclusions.']}},
    {week: 7, start: '2026-11-23', phase: 'Communication', title: 'Dashboards and data storytelling',
      activities: 'Design the dashboard for a non-specialist audience. Peer feedback between teams.',
      deliverable: {name: 'Dashboard draft and feedback to another team', who: 'Team', format: 'Dashboard link or PDF + half-page feedback (PDF)',
        include: ['A first version of your dashboard: question, main charts and key messages.',
          'Written feedback on the dashboard of the team you are paired with, answering: Is it clear? Is it correct? What would you improve?']}},
    {week: 8, start: '2026-11-30', phase: 'Communication', title: 'Final dashboard and rehearsal',
      activities: 'Incorporate feedback, prepare the presentation, rehearse online.',
      deliverable: {name: 'Final dashboard and slides', who: 'Team', format: 'Dashboard link or PDF + slides (maximum 10 slides, 10-minute presentation)',
        include: ['Your question, the data and the methods.',
          'Your three key findings.',
          'Limitations and what a policy-maker could learn from your results.',
          'Who presents which part (every team member presents).']}},
    {week: 9, start: '2026-12-07', phase: 'Presentation', title: 'Joint online presentation and reflection',
      activities: 'All teams present to students and teachers from the three universities. Closing discussion.',
      deliverable: {name: 'Final presentation and final reflection', who: 'Team (presentation) + individual (reflection)', format: 'Live online presentation + one-page PDF reflection',
        include: ['Take part in the joint online presentation: this is required to receive the extra points.',
          'Final individual reflection (300–400 words): what did you learn about data analysis, about working internationally and about yourself?']}},
  ],

  // Why join: shown on the home page and in the PDF
  benefits: [
    {title: 'Extra points on your grade', text: 'Up to 1 extra point (out of 10) at the University of Seville, and up to 10 extra points (out of 100) at the Technical University of Košice and the University of Montenegro, for students who complete the final presentation.'},
    {title: 'Certificate of participation', text: 'Students who complete the COIL receive a certificate of participation in a Ulysseus European University COIL, which you can add to your CV and LinkedIn.'},
    {title: 'An international experience without travelling', text: 'Work for nine weeks with students from Spain, Slovakia and Montenegro, from your own classroom.'},
    {title: 'A real project for your portfolio', text: 'You will analyse real European data and build a dashboard you can show to future employers. The best projects are published on this website.'},
    {title: 'Skills employers ask for', text: 'Data analysis with Python or R, dashboards, teamwork in international and online teams, and presenting in English.'},
    {title: 'A head start for your final project', text: 'You can develop your COIL project further in your bachelor\'s thesis (Trabajo Fin de Grado or equivalent), in agreement with your supervisor: you will already have the question, the data and the first analyses.'},
    {title: 'A step towards international internships', text: 'An international project, teamwork in English and contacts in three countries are a strong point when you apply for internships abroad, such as Erasmus+ traineeships.'},
    {title: 'Your Ulysseus network', text: 'Meet students and teachers from other Ulysseus universities: a first step towards an Erasmus exchange or further European projects.'},
  ],

  // Example projects: ideas that work with the COIL dataset (teams may propose their own)
  examples: [
    {title: 'Education and youth unemployment', question: 'Do countries with more young people in higher education have lower youth unemployment?',
      indicators: ['SL.UEM.1524.ZS', 'SE.TER.ENRR', 'NY.GDP.PCAP.PP.KD'], methods: 'Regression on the country panel; compare Spain, Slovakia and Montenegro with the European pattern.'},
    {title: 'The digital divide in Europe', question: 'Which European countries are digital leaders and which are lagging behind, and does it depend on income?',
      indicators: ['IT.NET.USER.ZS', 'IT.NET.BBND.P2', 'NY.GDP.PCAP.PP.KD'], methods: 'Correlation, then clustering of countries by their digital profile.'},
    {title: 'Ageing and public spending', question: 'Do older societies spend more on health, and do they have more public debt?',
      indicators: ['SP.POP.65UP.TO.ZS', 'SH.XPD.CHEX.GD.ZS', 'GGXWDG_NGDP'], methods: 'Regression with time trends; discuss differences in welfare systems.'},
    {title: 'Women in the labour market', question: 'Is higher female participation in the labour market linked to fertility and income across Europe?',
      indicators: ['SL.TLF.CACT.FE.ZS', 'SP.DYN.TFRT.IN', 'NY.GDP.PCAP.PP.KD'], methods: 'Regression and classification of countries into high and low participation groups.'},
    {title: 'The green transition', question: 'Are richer countries greener? Renewable energy and income in Europe.',
      indicators: ['EG.FEC.RNEW.ZS', 'NY.GDP.PCAP.PP.KD', 'EN.GHG.CO2.PC.CE.AR5'], methods: 'Regression and clustering. Note: there are no CO2 data for Montenegro, so explain how you deal with it.'},
    {title: 'Inequality and the structure of the economy', question: 'Are economies with a larger service sector more or less unequal?',
      indicators: ['SI.POV.GINI', 'NV.SRV.TOTL.ZS', 'NY.GDP.MKTP.KD.ZG'], methods: 'PCA to summarise the economic structure, then clustering.'},
  ],

  // Templates referred to in the weekly deliverables
  templates: [
    {title: 'Template: topic proposal (week 2)', items: ['Team name and members (name, university).', 'Research question (one sentence, ending with a question mark).',
      'Why it matters for Spain, Slovakia and Montenegro (3–4 sentences).', 'Indicators: name and code of 3–6 indicators from the COIL dataset.',
      'Countries and years you will use.', 'Methods you expect to use.', 'Possible problems (missing data, comparability) and how you will handle them.']},
    {title: 'Template: team charter (week 2)', items: ['Our goal as a team.', 'Roles for the first weeks (coordinator, data lead, analyst, visualisation lead, editor) and when we will rotate them.',
      'Communication channel and maximum answer time.', 'Weekly meeting day and time (CET).', 'How we take decisions.', 'What we do if a member does not contribute or misses a deadline.']},
    {title: 'Template: data dictionary (week 3)', items: ['One row per variable with these columns: variable name · indicator code · definition · unit · source · years covered · missing values and how they were handled.']},
  ],

  // Student guide: one block per topic. text = paragraphs; items = bullet points (both optional).
  guide: [
    {title: 'What is this COIL and what will you do?',
      text: ['A COIL (Collaborative Online International Learning) connects your course with courses at two partner universities of the Ulysseus alliance. For nine weeks you will work online in an international team with students from Seville, Košice and Podgorica.',
        'Together you will choose a socio-economic question, analyse real data from European countries with the methods of the course, build a dashboard and present your results to everybody in a joint online session. The COIL is part of your own course: you receive credits and are graded by your home university.']},
    {title: 'Before you start: checklist',
      items: ['Read this guide and the schedule.',
        'Make sure you can use Python or R, and Power BI if your course uses it.',
        'Download the COIL dataset from the Data section and open it once.',
        'Join the COIL team on Microsoft Teams (you will receive an invitation) and check that your camera and microphone work.',
        'Prepare a short personal profile: who you are, what you study, what you are good at and what you want to learn.']},
    {title: 'Working in an international team',
      text: ['Spain, Slovakia and Montenegro are in the same time zone (CET), so scheduling meetings is easy. Cultural and academic habits may differ, and that is part of the learning.'],
      items: ['Agree on one main communication channel and answer messages within 48 hours on working days.',
        'Meet online at least once a week and write down what was decided and who does what.',
        'Use English in all team communication, so that nobody is left out.',
        'Rotate roles every two or three weeks: coordinator, data lead, analyst, visualisation lead and editor.',
        'Write a team charter in week 2: goals, roles, deadlines, how you take decisions and what you do if someone does not contribute.',
        'If a problem in the team cannot be solved within the team, tell your teacher early.']},
    {title: 'The project step by step',
      items: ['Weeks 1–2: get to know each other, form teams and choose a question that can be answered with data from several countries.',
        'Weeks 3–4: prepare the data and explore it. Document every variable and every change you make.',
        'Weeks 5–6: apply the methods of the course (regression, classification, dimensionality reduction and clustering) and interpret the results in each national context.',
        'Weeks 7–8: turn your results into a clear dashboard for a non-specialist audience and give feedback to another team.',
        'Week 9: present to students and teachers of the three universities and write your final reflection.']},
    {title: 'Using the data',
      items: ['Start from the COIL dataset; you may add other sources if you document them.',
        'Always cite the source of each indicator (World Bank, IMF, Eurostat…).',
        'Some indicators have gaps, especially for Montenegro. Do not fill them in silently: either leave them out or explain clearly what you did.',
        'Check units and years before comparing countries.',
        'Correlation is not causation: be careful with your conclusions.']},
    {title: 'Deliverables and assessment',
      text: ['There is one deliverable each week (see the schedule). Each university grades its own students.',
        'The COIL gives you additional points on top of your course grade: up to 1 extra point (out of 10) at the University of Seville, and up to 10 extra points (out of 100) at the Technical University of Košice and the University of Montenegro. The extra points are awarded to students who complete the final presentation of the project in week 9.'],
      items: ['Every deliverable is due on Sunday at 23:59 CET of its week, and is submitted in the COIL team on Microsoft Teams (one assignment per week).',
        'If you cannot meet a deadline, tell your team and your teacher before the deadline, not after.',
        'Final dashboard: an interactive link, or a PDF or screenshots if Power BI publishing is not allowed in your university account.',
        'The final team projects will be shown in the Projects section of this website (team name and topic only, no personal data).']},
    {title: 'Reflection',
      text: ['You will write a short reflection at the start, in the middle and at the end of the COIL. Some questions to guide you:'],
      items: ['What did you expect from working with students from other countries, and what actually happened?',
        'How did cultural or institutional differences change the way your team read the data?',
        'What would you do differently in an international team next time?',
        'Which skill (technical or personal) improved the most?']},
    {title: 'Academic integrity and AI tools',
      items: ["Your work must be your own and your team's. Cite all sources, data and code you reuse.",
        'Follow the rules of your home university on the use of AI tools, and say clearly when and how you used them.',
        'Every team member must be able to explain the analysis and the results.']},
    {title: 'Questions and contact',
      text: ['For anything about grades, deadlines or your course, contact your teacher at your home university (see the Teaching team section). For questions about the joint activities or the dataset, any teacher of the COIL can help you.']},
  ],

  // Team projects, added by the teachers after each team submits its link.
  // {team, universities: ['US','TUKE','UoM'], topic, link, image}
  projects: [],

  resources: [
    {title: 'Ulysseus COIL Handbook: A Practical Guide for Educators',
      url: 'https://ulysseus.eu/wp-content/uploads/2025/02/Ulysseus-COIL-Handbook-for-teachers-1.pdf'},
    {title: 'World Bank Open Data (source of most indicators)', url: 'https://data.worldbank.org'},
    {title: 'IMF DataMapper (government debt)', url: 'https://www.imf.org/external/datamapper'},
    {title: 'Eurostat database (more European indicators)', url: 'https://ec.europa.eu/eurostat/data/database'},
  ],
};
